cernanalysispreservation/analysispreservation.cern.ch

- invenio_data/base/fixtures/websearch.py
- invenio_data/base/templates/search/searchbar_frame.html
* Adds ATLAS collection to the tree and ATLAS logo to the home
page.  (closes #31)
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
> templates: addition of ATLAS collection and logo

- cap/modules/fixtures/cli.py
- cap/modules/fixtures/data/records.json
* It updates all the values of the field parameters.value in order to
be compliant with the ElasticSearch mapping.
* Fixes the indentation of the records fixture command.
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>
> fixtures: records cli indentation fix

- CONTRIBUTING.rst
Adds a description for kwalitee and a more detailed description on how to write commit messages. Removes links that include Invenio-specific linking/descriptions such as their Github Issue list.
Remark: If ever Github allows using `.. include:: file` we should include `.kwalitee.yml` instead of linking to it.
> docs: update contribution guide

- INSTALL.rst
Solution adopted from https://github.com/inspirehep/inspire-next/commit/b566ed71f3b54c55071040e5380337623a16a76f.
Fix for the homepage looking like that:
> docs: fix node-sass version

- cap/modules/theme/static/scss/cap.scss
- cap/modules/theme/templates/cap_theme/home.html
Noticed the same bug as in https://github.com/cernanalysispreservation/analysis-preservation.cern.ch/pull/363 still remained on the middle page for the same reason, yet other part of the scss, so here's the fix.
> UI: fix footer on middle page/home

- docker-compose-dev.yml
* put breakpoints in your code
* use the command ```docker attach CONTAINER_ID``` to attach to the container from your terminal
* debug
* to exit use ```CONTROL + P, CONTROL + Q``` - this will detach from container without killing it (```CONTROL + C``` will stop the container)
> docker: enable debugging with pdb

- INSTALL.rst
Copying the files solves this error: "ERROR: Service 'nginx' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder385278945/ssl.key: no such file or directory"
> dev: update install.rst

- .travis.yml
* after Travis CI uses as default Ubuntu 'xenial'
* https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
> travis: pins distro to 'trusty'

- cap/modules/deposit/loaders.py
- tests/integration/test_create_deposit.py
* all _ fields are populated by the backend, hence should be ignored in requests
* also removed remainings after x-cap files logic
> deposit: remove underscore prefixed fields from requests data

- cap/jsonschemas/definitions/indico-events-v0.0.1.json
- cap/modules/services/serializers/__init__.py
- cap/modules/services/serializers/indico.py
- cap/modules/services/test_responses/responses.py
- cap/modules/services/views/__init__.py
- cap/modules/services/views/indico.py
- cap/modules/services/views/status_checks.py
- tests/integration/test_indico_views.py
* closes #1205
Includes implementation of the Indico service endpoint and serializer,
and implementation of the corresponding status check.
> services: add indico service view prototype

- ui/src/actions/auth.js
Update the initCurrentUser(next).
When the next is not defined, it means that we do not want to redirect.
That skips the problem with the redirection on reload to /undefined
> UI: redirection onreload to undefined fixed

- .coveragerc
- cap/modules/experiments/utils/cadi.py
- tests/unit/experiments/test_cadi_utils.py
> CMS: give write access to harvested cadi entries to cms admin egroup

- cap/config.py
- cap/modules/deposit/api.py
- cap/modules/deposit/serializers/__init__.py
- cap/modules/deposit/serializers/json.py
- cap/modules/deposit/serializers/schemas/__init__.py
- cap/modules/deposit/serializers/schemas/json.py
- cap/modules/deposit/utils.py
- cap/modules/records/api.py
- cap/modules/records/links.py
- cap/modules/records/permissions.py
- cap/modules/records/serializers/__init__.py
- cap/modules/records/serializers/schemas/common.py
- cap/modules/records/utils.py
- cap/modules/schemas/models.py
- cap/modules/schemas/serializers.py
- cap/modules/schemas/views.py
- tests/conftest.py
- tests/integration/test_clone_deposits.py
- tests/integration/test_create_deposit.py
- tests/integration/test_get_deposits.py
- tests/integration/test_get_records.py
- tests/integration/test_publish_deposit.py
- tests/integration/test_schemas_views.py
- tests/integration/test_serializers.py
- tests/integration/test_update_deposit.py
* split serializers for records and deposit
* fixes problem with missing links on publish
* fixes missing links on post when pid not given
* fixes problem with serializing when bucket doesnt exist
* hides _ fields from serializers metadata
* $schema string replaced with -> {schema: 'name', version: '1.0.0'} so doesnt required parsing on front
> serializers: fixes for deposits and records serializers

- .travis.yml
- cap/modules/deposit/links.py
- cap/modules/deposit/serializers/json.py
- cap/modules/deposit/serializers/schemas/json.py
- cap/modules/records/links.py
- cap/modules/records/serializers/schemas/common.py
- cap/modules/records/serializers/schemas/json.py
- cap/modules/schemas/resolvers.py
- cap/modules/user/utils.py
- cap/profilers.py
- setup.py
- tests/conftest.py
- tests/integration/test_clone_deposits.py
- tests/integration/test_create_deposit.py
- tests/integration/test_edit_published_deposit.py
- tests/integration/test_get_deposits.py
- tests/integration/test_get_records.py
- tests/integration/test_publish_deposit.py
- tests/integration/test_serializers.py
- tests/integration/test_update_deposit.py
* get rid of can_update, can_admin
* use is_owner instead
* cache links factories
* cache user and roles names
* closes #1352
> global: optimize deposits and records serializers

- ui/src/components/drafts/form/themes/grommet-preview/templates/FieldTemplate.js
- ui/src/components/drafts/form/themes/grommet-preview/widgets/TextWidget.js
- ui/src/components/partials/SectionBox.js
Added CSS rule wordBreak: break-all
> ui: draft preview word break to be responsive

- cap/config.py
- cap/modules/deposit/api.py
- cap/modules/experiments/utils/cadi.py
- cap/modules/fixtures/schemas/alice-analysis.json
- cap/modules/fixtures/schemas/atlas.json
- cap/modules/fixtures/schemas/cms-questionnaire.json
- cap/modules/fixtures/schemas/cms.json
- cap/modules/fixtures/schemas/lhcb.json
- cap/modules/records/serializers/schemas/common.py
- cap/modules/records/serializers/schemas/json.py
- tests/integration/test_get_records.py
- tests/integration/test_publish_deposit.py
- tests/integration/test_serializers.py
- ui/src/components/dashboard/DashboardQuickSearch.js
- ui/src/components/drafts/DraftEditor.js
- ui/src/components/drafts/DraftPreview.js
- ui/src/components/published/PublishedPreview.js
- ui/src/components/search/SearchResults.js
* add fields to schema to keep track of harvested entries
* once user edited harvested record, set _user_edited flag
* add quick search query for CMS to get all the cadi entries
* closes #1419
> deposits: add _fetched_from and _user_edited fields to schemas and mappings

- cap/modules/experiments/cli.py
- cap/modules/experiments/tasks/cms.py
- cap/modules/experiments/utils/common.py
- cap/modules/experiments/utils/das.py
- requirements.txt
* don't load in memory the whole set of datasets
* harvest das from all instances done in #1434
* closes #1422
> cms: index datasets in batches

- cap/modules/fixtures/schemas/cms.json
- ui/src/components/drafts/form/themes/grommet/templates/FieldTemplate.js
- ui/src/components/drafts/form/themes/grommet/templates/TabField.js
CMS UPDATES:
* remove the Accordion Field
* check if there is uiSchema first, before checking the ui:options object
> ui: form fields updates

- ui/src/components/drafts/DraftEditor.js
- ui/src/components/drafts/DraftPreview.js
- ui/src/components/drafts/components/Buttons/Anchors.js
- ui/src/components/drafts/components/Buttons/EditAnchor.js
- ui/src/components/drafts/components/Buttons/index.js
- ui/src/components/partials/SectionBox.js
- ui/src/components/published/PublishedPreview.js
Created a new Anchors component in order to pass the link as a parameter.
There are many buttons in the folder that could be easily merged to one with parameters since the share same attributes. Needs further investigation.
> ui:  add report links to the preview

- cap/modules/repos/serializers.py
- cap/modules/repos/views.py
- tests/integration/test_view_for_github_webhooks.py
- tests/integration/test_view_for_gitlab_webhooks.py
> repos: create separate payload serializers for release and push events

- ui/src/components/drafts/DraftPreview.js
- ui/src/components/partials/SectionBox.js
- ui/src/styles/styles.scss
* make the DraftPreview links (Metadata, Repositories, Workflows) visible in smaller screens
> ui: draftPreview links visible in smaller screens

- ui/cap-react/src/components/search/SearchFacet/SearchFacet.js
- ui/cap-react/src/components/search/SearchFacets.js
> ui: update search shortcut url, for published records

- ui/cap-react/src/components/drafts/DraftPreview.js
- ui/cap-react/src/components/drafts/form/JSONSchemaPreviewer.js
- ui/cap-react/src/components/partials/SectionBox.js
- ui/cap-react/src/styles/styles.scss
* ui: update the media queries for the edit page
* ui: css fixes for jsonschemapreviewer
* ui: draftItem - change metadata preview mode to 'list'
closes #1863, closes #1871
> ui: JSONSchemaPreviewer layout fixes

- ui/cap-react/src/components/drafts/form/themes/grommet/components/FormLayer.js
- ui/cap-react/src/components/drafts/form/themes/grommet/widgets/RadioWidget.js
- ui/cap-react/src/styles/styles.scss
* Before
* After
* closes #1885
> ui: fix grommet horizontal padding for small screens

- cap/modules/deposit/serializers/__init__.py
- cap/modules/deposit/serializers/schemas/json.py
- cap/modules/records/serializers/schemas/common.py
- cap/modules/records/serializers/schemas/json.py
- scripts/cap.wordlist
- tests/integration/deposits/test_get_deposits.py
* uses a new serializer for search, that does not include
all the profile info in the `access` field
> deposits: add serializer for deposit `access`

- cap/modules/services/views/cern.py
Properly encoding `query` while formatting `ldap_query` will avoid a LDAP Injection which could allow an attacker to leak information.
> Escape search filter's user input in LDAP query

- .githooks/prepare-commit-msg
- .pre-commit-config.yaml
- CONTRIBUTING.rst
- docker-compose.dev.yml
- ui/cap-react/package.json
- ui/cap-react/src/antd/App/App.js
- ui/cap-react/src/antd/routes/index.js
- ui/cap-react/src/antd/schemas/Schemas.js
- ui/cap-react/src/antd/schemas/index.js
- ui/cap-react/src/antd/util/CodeEditor.js
- ui/yarn.lock
Closes #2669 adding a page to display schemas (e.g. `/schemas/cms-analysis[/0.0.1]`) and edit them, only allowing edition of certain allowed fields. It also lets you check the diff and revert the current changes before saving.
> ui: display and edit schemas

- ui/cap-react/src/antd/admin/components/AdminPanel.js
- ui/cap-react/src/antd/admin/components/Header.js
- ui/cap-react/src/antd/admin/components/HeaderMenuItem/HeaderMenuItem.js
- ui/cap-react/src/antd/admin/components/HeaderMenuItem/HeaderMenuItem.less
- ui/cap-react/src/antd/admin/containers/Header.js
Change the look of the admin toolbar to differentiate it from the app toolbar (and to improve a bit the looks on mobile, even though this is not our priority). Also fixed a bug that was causing the routing to break when clicking several times in a row in either "Form Builder" or "Notifications".
Signed-off-by: Miguel Garcia Garcia <miguel.garcia.garcia@cern.ch>
> ui: change the looks of the admin toolbar

- ui/cap-react/src/antd/App/App.less
- ui/cap-react/src/antd/admin/components/Customize.js
- ui/cap-react/src/antd/admin/components/FormPreview.js
- ui/cap-react/src/antd/admin/components/PropKeyEditorForm.js
- ui/cap-react/src/antd/admin/components/PropertyEditor.js
- ui/cap-react/src/antd/admin/components/SchemaPreview.js
- ui/cap-react/src/antd/admin/components/SchemaWizard.js
- ui/cap-react/src/antd/admin/components/SelectFieldType.js
- ui/cap-react/src/antd/admin/formComponents/widgets/SliderWidget.js
- ui/cap-react/src/antd/admin/formComponents/widgets/index.js
- ui/cap-react/src/antd/admin/utils/fieldTypes.js
- ui/cap-react/src/antd/admin/utils/index.js
- ui/cap-react/src/antd/admin/utils/schemaSettings.js
- ui/cap-react/src/antd/collection/CollectionPermissionItem.js
- ui/cap-react/src/antd/drafts/components/Connect/Connect.js
- ui/cap-react/src/antd/drafts/components/Overview/Overview.js
- ui/cap-react/src/antd/drafts/components/SideBar/DraftSideBar.js
- ui/cap-react/src/antd/drafts/components/SideBar/SideBar.js
- ui/cap-react/src/antd/forms/fields/CapFiles.js
- ui/cap-react/src/antd/forms/templates/ArrayFieldTemplates/EmptyArrayField.js
- ui/cap-react/src/antd/forms/templates/Field/FieldTemplate.js
- ui/cap-react/src/antd/forms/templates/ObjectFieldTemplate.js
- ui/cap-react/src/antd/partials/EditableField/EditableField.js
- ui/cap-react/src/antd/partials/FileList/components/Files.js
- ui/cap-react/src/antd/settings/components/Applications.js
- ui/cap-react/src/components/search/SearchPage.js
Closes #2681
* Removed unnecessary margins in the PropKeyEditor (aka left column).
* Added tabs to the PropKeyEditor instead of having two collapsible sections one for schema settings and one for ui schema settings.
* Added a PopConfirm to the field delete button, instead of the old dialog.
* Replaced the tags indicating the "path" of the field in the tree with breadcrumbs. The title is now shown in a new line instead of as an editable tag (it's still inline editable).
* Replaced the select for the readonly setting with a switch.
* Replaced the select for the field width ui setting with a slider.
* Moved the gear icon on top of the field tree to the right and made it an actual button. This is for editing the schema settings for the root field. The UI settings that were hardcoded at the …
> ui: admin layout changes

- ui/cap-react/package.json
- ui/cap-react/src/antd/App/App.js
- ui/cap-react/src/antd/util/ErrorPage.js
- ui/cap-react/src/index.js
- ui/yarn.lock
Closes #2106 
Added a root ErrorBoundary integrated with Sentry. Configured Sentry for the frontend in the central SIS instance (https://sentry.siscern.org/cap-cb/cap-ui-dev). The backend one should be moved there as well when possible.
**To do in the future:**
To be able to see the actual source code in the sentry traces, we have to upload the sourcemaps. We should check it in the future since it will require some changes to the build script and defined release names.
> ui: Add root ErrorBoundary and configure Sentry

- ui/cap-react/src/actions/schemaWizard.js
- ui/cap-react/src/antd/admin/formComponents/SchemaTreeItem.js
Closes #2736 
- Now the primary text in the tree items is the key of the field, and the secondary text, which is now the title, has been moved to another line. The title will only be displayed when there is one.
- Added ellipsis to both texts and prevented them from overflowing
- Now it's not possible to add spaces when editing the key. If you try adding them, the changes are not going to be saved and a warning will be displayed
> ui: fix overflow in schema tree item

- cap/modules/fixtures/schemas/cms.json
- ui/cap-react/cypress/e2e/formBuilder/formBuilder_spec.js
- ui/cap-react/cypress/routes/index.js
- ui/cap-react/src/actions/schemaWizard.js
- ui/cap-react/src/antd/App/App.js
- ui/cap-react/src/antd/admin/Admin.js
- ui/cap-react/src/antd/admin/components/PropKeyEditorForm.js
- ui/cap-react/src/antd/admin/components/SelectContentType.js
- ui/cap-react/src/antd/admin/containers/SelectContentType.js
- ui/cap-react/src/antd/admin/utils/fieldTypes.js
- ui/cap-react/src/antd/admin/utils/index.js
- ui/cap-react/src/antd/forms/templates/ArrayFieldTemplates/ImportListModal.js
- ui/cap-react/src/antd/forms/templates/ArrayFieldTemplates/LayerArrayFieldTemplate.js
- ui/cap-react/src/antd/forms/widgets/SelectWidget.js
- ui/cap-react/src/antd/routes/index.js
- ui/cap-react/src/antd/schemas/components/Schemas.js
- ui/cap-react/src/antd/schemas/containers/Schemas.js
- ui/cap-react/src/antd/schemas/index.js
- ui/cap-react/src/antd/utils/index.js
* closes #2765  
* closes #2848
> PR 2747 2848

- ui/cap-react/src/antd/dashboard/components/Dashboard.js
- ui/cap-react/src/antd/drafts/components/DraftItemNav/NavMenu.js
Closes #2871 
- Removed the workflows list from the dashboard and rearranged it
- Removed the disabled workflows button from the drafts side bar
> ui: visually remove workflows

- cap/modules/fixtures/schemas/cms-questionnaire.json
- ui/cap-react/src/antd/drafts/components/DraftHeader/DraftHeader.js
- ui/cap-react/src/antd/published/components/Preview.js
- ui/cap-react/src/antd/published/containers/Preview.js
> ui: add published date to preview header
