CONTRIBUTING.rst
DEVELOPING.rst
README.rst

- docs: better README file
- docs: addition of contributing guides

docs: better README file

---

docker-compose-dev.yml
invenio_data/base/bundles.py
invenio_data/config.py
invenio_data/modules/deposit/forms/alice.py
invenio_data/modules/deposit/forms/cms.py
invenio_data/modules/deposit/forms/cmsquestions.py
invenio_data/modules/deposit/forms/cmsquestions2.py
invenio_data/modules/deposit/forms/lhcb.py
invenio_data/modules/deposit/workflows/questions2.py
invenio_data/modules/jsondeposit/bundles.py
invenio_data/modules/jsonedit/bundles.py
invenio_data/modules/jsonedit/views.py
requirements.txt
setup.py

* Fixes installation with newest Invenio.
Signed-off-by: Marco Neumann <marco@crepererum.net>

global: sync with latest Invenio

---

invenio_data/base/bundles.py
invenio_data/base/fixtures/accounts.py
invenio_data/config.py
invenio_data/modules/deposit/workflows/cms.py
invenio_data/modules/deposit/workflows/lhcb.py
invenio_data/modules/deposit/workflows/questions.py
invenio_data/modules/deposit/workflows/questions2.py
invenio_data/modules/jsondeposit/bundles.py
invenio_data/modules/jsonedit/bundles.py
requirements.txt
setup.py

* Updates dependencies to use the stable versions.
* Freeze Sorteable library due to issue with
its last version.
* Internal references updated in order to work
with the latest invenio.
Co-authored-by: Pamfilos Fokianos <pamfilos.fokianos@cern.ch>
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>

global: stabilization with latest invenio

---

cap/modules/access/views.py
cap/modules/alpaca/static/js/invenio-alpaca.js
cap/modules/alpaca/static/js/jsonwidget-create.js
cap/modules/alpaca/static/js/jsonwidget-edit.js
cap/modules/alpaca/static/scss/invenio-alpaca-edit.scss
cap/modules/alpaca/static/templates/container-object-autocomplete-import.html
cap/modules/alpaca/static/templates/container-oneOf.html
cap/modules/records/jsonschemas/definitions/docker-enc-schema.json
cap/modules/records/jsonschemas/definitions/fromattr-pub-schema.json
cap/modules/records/jsonschemas/definitions/fromyaml-pub-schema.json
cap/modules/records/jsonschemas/definitions/nodemap-scheduler-schema.json
cap/modules/records/jsonschemas/definitions/stage-schema.json
cap/modules/records/jsonschemas/definitions/step-schema.json
cap/modules/records/jsonschemas/definitions/stringinterp-schema.json
cap/modules/records/jsonschemas/definitions/workflow-schema.json
cap/modules/records/jsonschemas/options/ATLASWorkflows.js
cap/modules/records/jsonschemas/records/ATLASWorkflows.json

WIP: 'oneOf' feature in AlpacaJS, ATLAS workflows, CMS questionnaire updates

---

cap/config.py
cap/modules/alpaca/static/js/jsonwidget-edit.js
cap/modules/alpaca/static/scss/invenio-alpaca-edit.scss
cap/modules/records/ext.py
cap/modules/records/fetchers.py
cap/modules/records/indexer.py
cap/modules/records/jsonschemas/options/LHCbAnalysis.js
cap/modules/records/jsonschemas/records/LHCbAnalysis.json
cap/modules/records/mappings/cmsanalysis.json
cap/modules/records/mappings/cmsquestionnaire.json
cap/modules/records/mappings/lhcbanalysis.json
cap/modules/records/minters.py
cap/modules/records/serializers/__init__.py
cap/modules/records/serializers/schemas/__init__.py
cap/modules/records/serializers/schemas/json.py
cap/modules/records/templates/records/detail.html
cap/modules/records/templates/records/edit.html
cap/modules/records/views.py
requirements.txt
setup.py

* (Javier's) global: dependency updates to invenio-records-a12
* records: adds view_method for record_view
* records: updates 'json' field structure
* records: addition of serializers
* LHCb: updates placeholders in LHCb Analysis form

LHCb and records

---

cap/config.py
cap/modules/records/views.py
cap/modules/theme/static/js/records/controllers.js

* ability to add ‘E-Group’ permissions

records: adds ability to provide access by 'role'

---

.kwalitee.yml
.travis.yml
README.rst

* Adds `kwalitee` commit message check to the Travis CI process.
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

kwalitee: initial configuration

---

cap/modules/records/jsonschemas/options/CMSAnalysis.js
cap/modules/records/jsonschemas/records/CMSAnalysis.json

* added fields for AOD processing from Wei's feedback (issue #129)
* added field in basic information from Wei's feedback (issue #129)

CMS: fields for AOD processing

---

cap/modules/records/jsonschemas/definitions/CMSInputCodeOutput.json
cap/modules/records/jsonschemas/definitions/CMSMainMeasurements.json
cap/modules/records/jsonschemas/definitions/CMSnTupleProduction.json
cap/modules/records/jsonschemas/definitions/MonteCarloBackgroundDataset-vtest01.json
cap/modules/records/jsonschemas/definitions/MonteCarloDataset-vtest01.json
cap/modules/records/jsonschemas/definitions/MonteCarloSignalDataset-vtest01.json
cap/modules/records/jsonschemas/options/CMSAnalysis.js
cap/modules/records/jsonschemas/records/CMSAnalysis.json

* simplified the existing Input-Code-Output structure (choosing and transferring Input is work to be done yet)
* added Input Dataset field for a global Dataset list
* separated MC Signal and Background Datasets and Selections (Selections added to Datasets now)
* added basic information about the code - needs to be revised to look better
just a visual prototype yet!

Input-Code-Output Structure Update

---

cap/modules/records/jsonschemas/definitions/CMSAuxiliaryMeasurements.json
cap/modules/records/jsonschemas/definitions/CMSFinalInputCodeOutput.json
cap/modules/records/jsonschemas/options/CMSAnalysis.js
cap/modules/records/jsonschemas/records/CMSAnalysis.json

* updates to results and auxiliary measurements according to suggestions from @katilp

CMS: results and auxiliary update

---

cap/modules/records/jsonschemas/definitions/CMSAuxiliaryMeasurements.json
cap/modules/records/jsonschemas/definitions/CMSFinalInputCodeOutput.json
cap/modules/records/jsonschemas/definitions/CMSInputCodeOutput.json
cap/modules/records/jsonschemas/definitions/CMSMainMeasurements.json
cap/modules/records/jsonschemas/options/CMSAnalysis.js
cap/modules/records/jsonschemas/records/CMSAnalysis.json

* updates the schema according to discussion results
* name changes for understandability and correctness
* removes all but one dataset selection for the input that will include
all datasets
* adds larger description field

CMS: meeting updates for schema

---

cap/modules/records/jsonschemas/definitions/CMSAuxiliaryMeasurements.json
cap/modules/records/jsonschemas/definitions/CMSFinalInputCodeOutput.json
cap/modules/records/jsonschemas/definitions/CMSInputCodeOutput.json
cap/modules/records/jsonschemas/definitions/CMSMainMeasurements.json
cap/modules/records/jsonschemas/definitions/CMSUserCode.json
cap/modules/records/jsonschemas/options/CMSAnalysis.js
cap/modules/records/jsonschemas/records/CMSAnalysis.json

Updates on the form referencing #155.

CMS: form updates

---

cap/modules/alpaca/static/scss/invenio-alpaca-edit.scss
cap/modules/records/jsonschemas/definitions/CMSAuxiliaryMeasurements.json
cap/modules/records/jsonschemas/definitions/CMSMainMeasurements.json
cap/modules/records/jsonschemas/options/CMSAnalysis.js

* updates/adds final state physics objects and dependencies
* adds relations prototype (no physics object selection yet)
* references #155

CMS: final state dependencies

---

cap/modules/records/jsonschemas/definitions/CMSAuxiliaryMeasurements.json
cap/modules/records/jsonschemas/definitions/CMSMainMeasurements.json
cap/modules/records/jsonschemas/options/CMSAnalysis.js

* adds list of physics objects to relations
* adds missing types to physics objects
* references #155

CMS: relations update

---

cap/config.py
cap/modules/access/templates/access/login_user.html
cap/modules/access/views.py
cap/modules/alpaca/bundles.py
cap/modules/theme/templates/cap_theme/header_login.html
cap/modules/theme/templates/cap_theme/settings/base.html
cap/modules/theme/views.py
setup.py

* fixes dependencies to work with current overlay state (downgrades invenio-accounts, invenio-records, invenio-theme, after #144)

Fixes dependencies issues, updates account templates

---

.travis.yml
scripts/ref_url_validation.py

tests: adds script for validating $ref urls

---

.travis.yml

travis: configures travis to create db/collections

---

cap/modules/alpaca/static/scss/invenio-alpaca-edit.scss
cap/modules/records/jsonschemas/definitions/CMSAuxiliaryMeasurements.json
cap/modules/records/jsonschemas/definitions/CMSFinalInputCodeOutput.json
cap/modules/records/jsonschemas/definitions/CMSMainMeasurements.json
cap/modules/records/jsonschemas/definitions/CMSUserCode.json
cap/modules/records/jsonschemas/definitions/PrimaryDataset-vtest01.json
cap/modules/records/jsonschemas/options/CMSAnalysis.js
cap/modules/records/jsonschemas/records/CMSAnalysis.json

* adds missing fields, removes and changes wrong ones
* improves descriptions
* references #168 and #155 
still prototyping a form framework ready for testing but not yet for use

Including feedback basics

---

cap/config.py
cap/modules/fixtures/cli.py
cap/modules/fixtures/data/pages.json
cap/modules/fixtures/data/pages/about.html
cap/modules/fixtures/data/pages/terms.html
cap/modules/fixtures/pages.py
cap/modules/fixtures/utils.py
cap/modules/theme/templates/cap_theme/footer.html
setup.py

* Adds /about page.
* Adds /terms page.

fixtures: adds invenio-pages

---

.travis.yml
cap/config.py
scripts/init-db.sh

travis: adds script to recreate db

---

.coveragerc
cap/modules/fixtures/data/pages.json
tests/conftest.py
tests/unit/fixtures/test_fixtures_cli.py

tests: adds test for loadpages

---

cap/config.py
cap/modules/experiments/views/lhcb.py
setup.py

Signed-off-by: Ana Trisovic <ana.trisovic@cern.ch>

LHCb: methods for neo4j

---

Dockerfile
cap/config.py
cap/factory.py
cap/modules/alpaca/bundles.py
cap/modules/theme/static/js/cap-settings.js
docker-compose.yml
docker/nginx/conf.d/default.conf
requirements.txt
scripts/build-assets.sh
scripts/init-db.sh
scripts/init.sh
setup.py

* Updates the invenio-collections dependency to version 1.0.0a3.
* Updates the invenio-oauthclient dependency to version 1.0.0a8.
* Downgrades the Alpaca version to the previous one in order to
generate properly the assets.
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>

global: invenio-oauthclient dependency update

---

cap/modules/records/serializers/schemas/json.py

records: fixes issue in general title

---

cap/modules/alpaca/bundles.py
cap/modules/experiments/bundles.py
cap/modules/theme/bundles.py

see https://github.com/inveniosoftware/invenio-assets/issues/41

global: assets fix

---

setup.py

global: updates Flask to v0.11.1

---

cap/modules/records/jsonschemas/records/ATLASAnalysis-v0.0.1.json

ATLAS: Include Workflows schema in ATLAS Analysis schema

---

cap/config.py
cap/modules/access/loader.py

global: fixes oauth register issue

---

INSTALL.rst
cap/modules/alpaca/bundles.py
cap/modules/theme/static/js/cap-settings.js

docs: install guide update

---

INSTALL.rst

Adds a note to update the python eggs in case of requirements mismatch.

docs: update eggs note

---

cap/config.py
cap/modules/access/views.py
cap/modules/theme/templates/cap_theme/header_login.html
cap/modules/theme/templates/cap_theme/home.html
cap/modules/theme/views.py

access: redirect user to experiment

---

requirements.txt
setup.py

global: updates oauth version

---

cap/modules/alpaca/static/templates/container-array-item-display.html
cap/modules/alpaca/static/templates/container-array-item.html
cap/modules/alpaca/static/templates/container-depositgroup-array.html
cap/modules/alpaca/static/templates/container-depositgroup-object-array.html
cap/modules/alpaca/static/templates/container-depositgroup-object-quickfill-display.html
cap/modules/alpaca/static/templates/container-depositgroup-object-quickfill.html
cap/modules/alpaca/static/templates/container-depositgroup-object.html
cap/modules/alpaca/static/templates/container-depositgroup.html
cap/modules/alpaca/static/templates/container-object-autocomplete-import-display.html
cap/modules/alpaca/static/templates/container-object-autocomplete-import.html
cap/modules/alpaca/static/templates/container-oneOf.html
cap/modules/alpaca/static/templates/container.html
cap/modules/alpaca/static/templates/control-depositiongroup.html
cap/modules/alpaca/static/templates/control-mlt-choice-cb.html
cap/modules/alpaca/static/templates/control-mlt-choice-radio.html
cap/modules/alpaca/static/templates/control-tags-display.html
cap/modules/alpaca/static/templates/control-tags.html
cap/modules/alpaca/static/templates/control-url-harvest-display.html
cap/modules/alpaca/static/templates/control-url-harvest.html

removes licenses from templates, fixes records not loading

global: license fix templates

---

cap/modules/records/jsonschemas/definitions/CMSAuxiliaryMeasurements-v0.0.1.json
cap/modules/records/jsonschemas/definitions/CMSMainMeasurements-v0.0.1.json
cap/modules/records/jsonschemas/definitions/MonteCarloBackgroundDataset-v0.0.1.json
cap/modules/records/jsonschemas/definitions/MonteCarloSignalDataset-v0.0.1.json
cap/modules/records/jsonschemas/definitions/PrimaryDataset-v0.0.1.json
cap/modules/records/jsonschemas/options/CMSAnalysis-v0.0.1.js

CMS: schema update and fix

---

cap/modules/records/jsonschemas/options/LHCbAnalysis-v0.0.1.js
cap/modules/records/jsonschemas/records/LHCbAnalysis-v0.0.1.json

* updates schema according to LHCb feedback
* references #197
In status of waiting for more feedback/information. Requirements needed to continue work can be found in #197 . Help/information is welcome.

LHCb: basic post-feedback schema updates

---

cap/config.py
cap/modules/deposit/views/ui.py

* gives permissions to e-groups specified in the DEPOSIT_GROUP =><dep_group> => 'create_permission_roles'

deposit: add create permissions for deposit-groups

---

cap/config.py

deposit: add facets, search options

---

cap/config.py
cap/modules/theme/static/scss/cap.scss
cap/modules/theme/static/scss/frontpage.scss
cap/modules/theme/templates/cap_theme/header.html
cap/modules/theme/templates/cap_theme/header_login.html

UI: implements new navbar

---

cap/config.py
cap/modules/deposit/templates/cap_deposit/edit.html
cap/modules/deposit/views/ui.py
cap/static/templates/cap_deposit/actions.html

deposit: removes delete action

---

scripts/init-db.sh

global: improves initialization script

---

cap/config.py
cap/modules/access/permissions.py
cap/modules/deposit/permissions.py
cap/modules/deposit/views/ui.py
cap/modules/experiments/permissions/__init__.py
cap/modules/experiments/permissions/alice.py
cap/modules/experiments/permissions/atlas.py
cap/modules/experiments/permissions/cms.py
cap/modules/experiments/permissions/lhcb.py
cap/modules/experiments/views/alice.py
cap/modules/experiments/views/atlas.py
cap/modules/experiments/views/cms.py
cap/modules/experiments/views/lhcb.py
cap/utils.py
setup.py

deposit: add permissions by deposit group

---

cap/modules/theme/static/scss/cap.scss
cap/modules/theme/static/scss/footer.scss
cap/modules/theme/static/scss/variables.scss
cap/modules/theme/templates/cap_theme/footer.html

UI: implements new footer

---

tests/conftest.py
tests/unit/deposit/test_deposit_index.py

deposit: adds test for deposit index

---

cap/cli.py
cap/compilers.py
cap/config.py
cap/jsonschemas/deposits/records/cms-deposit-src.json
cap/jsonschemas/deposits/records/deposit-src.json
cap/jsonschemas/deposits/records/lhcb-deposit-src.json
cap/jsonschemas/test_schemas/subschema1-src.json
cap/jsonschemas/test_schemas/subschema1.json
cap/jsonschemas/test_schemas/subschema2.json
cap/jsonschemas/test_schemas/subschema3.json
cap/jsonschemas/test_schemas/test-expected.json
cap/jsonschemas/test_schemas/test-src.json
cap/jsonschemas/test_schemas/test.json
cap/utils.py
setup.py
tests/unit/test_resolve_jsonschemas.py

deposit: resolve jsonschemas

---

setup.py

travis: fixes broken package

---

cap/config.py
cap/modules/theme/static/scss/cap.scss
cap/modules/theme/templates/cap_theme/404.html
cap/modules/theme/templates/cap_theme/500.html
cap/modules/theme/views.py

UI: fixes misc pages templates

---

cap/modules/theme/static/scss/cap.scss
cap/modules/theme/static/scss/variables.scss

UI: adds new scrollbar

---

cap/config.py
cap/modules/deposit/templates/cap_deposit/edit.html
cap/static/templates/cap_records_js/actions.html
cap/static/templates/cap_records_js/alert.html

deposit: fixes response messages

---

cap/modules/access/views.py
cap/modules/theme/templates/cap_theme/header.html

deposit: add deposit groups to session

---

cap/config.py
cap/static/templates/cap_records_js/actions.html
scripts/init-db.sh

deposit: fixes actions

---

cap/config.py

global: transition from sqlite to postgres

---

cap/modules/access/views.py

deposit: fixes bug in groups

---

cap/config.py
cap/modules/cache/__init__.py
cap/modules/cache/ext.py
cap/modules/cache/proxies.py
setup.py

access: add access caching option

---

INSTALL.rst

Adds a small note on setting up postgresql in INSTALL.rst.

docs: add postgresql to install guide

---

cap/config.py
cap/jsonschemas/deposits/records/lhcb-v1.0.0.json
cap/jsonschemas/records/lhcb-v1.0.0.json
cap/mappings/deposits/records/lhcb-v1.0.0.json
cap/modules/deposit/api.py
cap/modules/deposit/links.py
cap/modules/deposit/templates/cap_deposit/edit.html
cap/modules/deposit/views/ui.py
cap/static/templates/cap_files_js/upload.html

deposit: fixes links

---

cap/modules/deposit/ext.py
cap/modules/deposit/indexers.py

deposit: index record in ES after being published

---

cap/config.py
setup.py

* also removes duplicate 'search-ui' dependency

deposit: adds permission for deposit views

---

cap/modules/theme/static/scss/cap.scss

fixes icon fonts broken by 6832546

UI: fix icons

---

cap/modules/theme/static/scss/cap.scss

I had quite some trouble with the scss but this works for me... Please check if it does so for you, I can improve on the style later.

UI: fix footer position

---

MANIFEST.in
cap/config.py
cap/modules/experiments/scripts/lhcb/get_publications_files.sh
cap/modules/experiments/scripts/lhcb/get_working_groups_files.sh
cap/modules/experiments/scripts/lhcb/lhcb.py
cap/modules/experiments/tasks.py
setup.py

install celery and add tasks for harvesting "databases" files for Working Groups and Publications databases

LHCb: Harvest dbs files

---

cap/modules/access/templates/access/login_user.html
cap/modules/deposit/views/ui.py
cap/modules/theme/static/scss/cap.scss
cap/modules/theme/static/scss/variables.scss
cap/modules/theme/templates/cap_theme/new_deposit_btn.html

global: general consistencies improvements

---

cap/jsonschemas/deposits/records/lhcb-v1.0.0.json
cap/jsonschemas/records/lhcb-v1.0.0.json
cap/static/json/deposits/records/lhcb-v1.0.0.json

deposit: fixes array with string fields

---

cap/modules/records/resolvers/jsonschemas.py
setup.py

schemas: add JSON-schema resolvers

---

cap/modules/fixtures/cli.py

fixtures: update permissions import

---

cap/static/json/deposits/records/cms-analysis-v1.0.0.json
cap/static/templates/cap_records_js/form.html

deposit: introduces optional display of elements

---

cap/modules/deposit/templates/cap_deposit/index.html
cap/modules/experiments/bundles.py
cap/modules/experiments/static/scss/experiments.scss
cap/static/js/cap/cap.app.js
cap/static/js/cap/cap.controllers.js
cap/static/templates/invenio_deposit/results.html
cap/templates/cap/header.html

UI: fixes ui inconsistencies

---

cap/jsonschemas/deposits/records/lhcb-v1.0.0.json
cap/modules/experiments/bundles.py
cap/modules/theme/static/scss/forms.scss
cap/static/js/cap/cap.app.js
cap/static/js/cap/cap.directives.js
cap/static/templates/cap_records_js/form.html

UI: adds progress bar in forms

---

cap/jsonschemas/deposits/records/cms-analysis-v1.0.0.json
cap/mappings/records/cms-analysis-v1.0.0.json
cap/modules/theme/static/scss/cap.scss
cap/modules/theme/static/scss/forms.scss
cap/static/js/cap/cap.controllers.js
cap/static/json/deposits/records/cms-analysis-v1.0.0.json
cap/static/templates/cap_records_js/form.html

UI: show/hide form elements on demand

---

cap/modules/theme/static/scss/forms.scss
cap/modules/theme/static/scss/header.scss
cap/static/js/cap/cap.controllers.js
cap/static/templates/cap_records_js/form.html

UI: adds search fields functionality 

---

cap/templates/cap/header.html

Quick fix for demo stamp overlapping brand link, references #385.

UI: fix brand link

---

cap/modules/theme/static/scss/forms.scss
cap/static/js/cap/cap.directives.js
cap/static/templates/cap_records_js/form.html

UI: fixes bug in progress bar

---

cap/config.py
cap/modules/deposit/query.py

deposit: restrict access to rest api

---

cap/config.py
cap/jsonschemas/deposits/records/cms-analysis-v1.0.0.json
cap/modules/deposit/views/ui.py
cap/modules/theme/static/scss/forms.scss
cap/static/js/cap/cap.controllers.js
cap/static/json/deposits/records/cms-analysis-v1.0.0.json
cap/static/templates/cap_records_js/decorators/tabarray.html
cap/static/templates/cap_records_js/form.html

UI: introduces tabarrays in fields

---

cap/modules/experiments/bundles.py
cap/modules/theme/static/scss/forms.scss
cap/static/js/cap/cap.directives.js
cap/static/js/cap/cap.factories.js
cap/static/templates/cap_records_js/decorators/array.html
cap/static/templates/cap_records_js/decorators/fieldset.html
cap/static/templates/cap_records_js/decorators/tabarray.html
cap/static/templates/cap_records_js/form.html

UI: introduces focus field on click

---

cap/modules/access/ext.py

access: use password for redis

---

CONTRIBUTING.rst

small improvement for encapsulation

docs: contribution guide update

---

cap/modules/theme/static/scss/forms.scss
cap/static/js/cap/cap.directives.js
cap/static/templates/cap_records_js/form.html

UI: fixes deposit dropdown

---

cap/config.py
cap/modules/deposit/views/ui.py
cap/modules/records/serializers/schemas/common.py

deposit: fixes reload of templates

---

cap/config.py
cap/jsonschemas/deposits/records/cms-analysis-v1.0.0.json
cap/modules/deposit/api.py
cap/modules/deposit/loaders.py
cap/static/js/cap/cap.main.js
cap/static/json/deposits/records/cms-analysis-v1.0.0.json
cap/static/templates/cap_records_js/decorators/button.html
cap/static/templates/cap_records_js/decorators/file_selector.html
setup.py

deposit: adds fetch files by url

---

Dockerfile
INSTALL.rst
MANIFEST.in
cap/modules/access/views.py
cap/modules/experiments/bundles.py
docker-compose-dev.yml
docker-compose.yml
docker/elasticsearch/Dockerfile
docker/nginx/conf.d/default.conf
scripts/build-assets.sh
setup.py

* Fixes Docker-based installation procedure by pinning `node-sass` and
`clean-css` and by introducing Gunicorn WSGI server that is now necessary
because of the multi-WSGI-app factory.
* Updates a few other installation commands and the documentation.
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

docker: fix Docker-based installation

---

cap/jsonschemas/deposits/records/cms-analysis-v1.0.0.json
cap/modules/deposit/api.py
cap/modules/deposit/loaders.py

Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>
Co-authored-by: Ioannis Tsanaktsidis  <ioannis.tsanaktsidis@cern.ch>

deposit: async url download

---

cap/modules/deposit/api.py
cap/static/templates/cap/recent_results.html

UI: adds messages when no results

---

cap/jsonschemas/deposits/records/cms-analysis-v1.0.0.json
cap/jsonschemas/deposits/records/cms-questionnaire-v1.0.0.json

deposit: fixes enum in cms analysis

---

cap/modules/experiments/static/js/experiments/app.js
cap/modules/theme/static/scss/cap.scss
cap/static/js/cap/cap.config.js
cap/static/js/cap/cap.controllers.js
cap/static/templates/cap/records/files_list.html
cap/static/templates/cap/records/record_detail.html
cap/static/templates/cap/shared_records.html
cap/static/templates/cap_records_js/form.html

UI: implements records page

---

cap/modules/experiments/static/js/experiments/app.js
cap/modules/theme/static/scss/forms.scss
cap/static/templates/cap_records_js/decorators/formAutofill.html

deposit: fix autofill

---

cap/mappings/records/atlas-workflows-v0.0.1.json

ATLAS: fixes mappings in workflows

---

cap/config.py
cap/modules/deposit/api.py
cap/modules/deposit/views/ui.py
cap/modules/experiments/static/js/experiments/app.js
cap/modules/records/serializers/schemas/common.py
cap/modules/theme/templates/cap_theme/header.html
cap/static/templates/cap/deposit/edit.html
cap/templates/cap/header.html

* fix issue in deposit/record transitions
* updates endpoint in header

deposit: fixes issue in draft/published transition

---

cap/jsonschemas/deposits/records/lhcb-v1.0.0.json
cap/jsonschemas/options/deposits/records/lhcb-v1.0.0.json

Co-authored-by: Anna Trzcinska <anna.trzcinska@cern.ch>

deposit: updates LHCb form

---

cap/config.py
cap/jsonschemas/definitions/alice-datasets-v0.0.1.json
cap/jsonschemas/definitions/main-analysis-v0.0.1.json
cap/jsonschemas/definitions/mc-analysis-v0.0.1.json
cap/jsonschemas/deposits/records/alice-analysis-v0.0.1.json
cap/jsonschemas/options/deposits/records/alice-analysis-v0.0.1.json
cap/jsonschemas/records/alice-analysis-v0.0.1.json
cap/mappings/deposits/records/alice-analysis-v0.0.1.json
cap/mappings/records/alice-analysis-v0.0.1.json

deposit: implements ALICE analysis

---

cap/static/js/cap/controllers/capCtrl.js
cap/static/templates/cap/experiments.html
cap/templates/cap/header.html
cap/templates/cap/searchbar.html

UI: removes experiments middle page

---

.travis.yml
cap/config.py
cap/jsonschemas/deposits/common/deposit-v1.0.0.json
cap/jsonschemas/deposits/records/atlas-analysis-v1.0.0.json
cap/jsonschemas/deposits/records/cms-analysis-v1.0.0.json
cap/jsonschemas/deposits/records/cms-questionnaire-v1.0.0.json
cap/jsonschemas/deposits/records/lhcb-v1.0.0.json
cap/mappings/deposits/records/alice-analysis-v0.0.1.json
cap/mappings/deposits/records/atlas-analysis-v1.0.0.json
cap/mappings/deposits/records/atlas-workflows-v0.0.1.json
cap/mappings/deposits/records/cms-analysis-v1.0.0.json
cap/mappings/deposits/records/cms-questionnaire-v1.0.0.json
cap/mappings/deposits/records/lhcb-v1.0.0.json
cap/mappings/records/atlas-analysis-v1.0.0.json
cap/modules/deposit/api.py
cap/modules/deposit/links.py
cap/static/js/cap/cap.config.js
cap/static/templates/cap/deposit/results.html
cap/static/templates/cap/recent_results.html
cap/static/templates/cap/records/results.html
cap/static/templates/cap_records_js/form.html
setup.py
tests/unit/deposit/test_deposit_index.py

deposit: implements clone functionality

---

.gitignore
setup.py
tests/conftest.py
tests/unit/deposit/test_deposit_index.py

tests: adds indexing test for all analyses

---

cap/jsonschemas/definitions/identifiers-v0.0.1.json

schemas: typo in schema filename

---

INSTALL.rst

Clean-up and update of the install guide to describe a full local install of CAP that should not require any further support or information from our side.

docs: update install guide

---

CONTRIBUTING.rst

Explain prod, qa and dev and how changes are propagated.

docs: add server structure explanation

---

cap/config.py
cap/mappings/deposits/records/alice-analysis-v0.0.1.json
cap/mappings/deposits/records/atlas-analysis-v0.0.1.json
cap/mappings/deposits/records/atlas-workflows-v0.0.1.json
cap/mappings/deposits/records/cms-analysis-v0.0.1.json
cap/mappings/deposits/records/cms-questionnaire-v0.0.1.json
cap/mappings/deposits/records/lhcb-v0.0.1.json
cap/modules/access/permissions.py
cap/modules/deposit/api.py
cap/modules/records/search.py

* return results by user collaboration

search: add records list permissions

---

cap/config.py
cap/modules/deposit/search.py

* returns deposit results if current_user is owner,  or has 'deposit-read' rights

search: add deposit list permission/filtering

---

cap/modules/deposit/api.py
cap/static/templates/cap/records/files_list.html

deposit: implements file list for records

---

cap/config.py
cap/modules/deposit/api.py
cap/modules/deposit/permissions.py
cap/modules/records/permissions.py

* gives REST permissions to collaboration users
considering record's schema attribute

records: add record item permissions

---

docs/api.yaml
docs/references/api.rst

First version of access token description, needs revising. I'm unsure about the actions scope.

docs: api docs

---

docs/backstage/docs-overview.rst
docs/backstage/swagger-overview.rst
docs/index.rst

This is a version of my documentation-related research work connected directly to the documentation here, as mentioned by @suenjedt.
I put in the link to the original as comment in case anyone wants to track potential changes. A submodule seemed to be over-complex for this matter.

docs: add research results

---

cap/modules/access/permissions.py

access: fix issue in admin permissions

---

cap/config.py
cap/static/scss/cap.scss
cap/static/templates/cap/components/capContentBar.html
cap/static/templates/cap/pushmenu/SubMenu.html
cap/static/templates/cap/recent_results.html

UI: fixes save button

---

cap/config.py
cap/static/js/cap/controllers/capDepositCtrl.js

deposit: populates data after saving

---

cap/static/js/cap/controllers/capDepositCtrl.js

deposit: adds state param

---

cap/modules/search_ui/templates/cap_search_ui/search.html
cap/static/js/cap/controllers/capDepositCtrl.js
cap/static/scss/cap.scss
cap/static/scss/forms.scss
cap/static/scss/pushmenu.scss
cap/static/templates/cap/deposit/results.html
cap/static/templates/cap/experiment_intro.html
cap/static/templates/cap/pushmenu/SubMenu.html
cap/static/templates/cap/shared_records.html
cap/static/templates/cap_records_js/decorators/array.html
cap/static/templates/cap_records_js/decorators/fieldset.html
cap/static/templates/cap_records_js/decorators/tabarray.html

UI: minor fixes

---

tests/conftest.py
tests/unit/deposit/test_deposit_api.py

tests: adds test for deposit publishing

---

cap/modules/deposit/api.py

deposit: fixes bug for clone functionality

---

cap/config.py
cap/modules/experiments/scripts/lhcb/lhcb.py

LHCb: fix parsing script for WG shelve files

---

cap/jsonschemas/options/deposits/records/alice-analysis-v0.0.1.json
cap/static/scss/forms.scss
cap/static/templates/cap/deposit/components/capDepositNavArray.html
cap/static/templates/cap/deposit/components/capDepositNavDefault.html
cap/static/templates/cap/deposit/components/capDepositNavObject.html
cap/static/templates/cap/deposit/components/depositSidebar.html
cap/static/templates/cap/recent_results.html
cap/static/templates/cap_records_js/decorators/array.html
cap/static/templates/cap_records_js/decorators/tabarray.html

UI: minor ui improvements

---

cap/modules/access/views.py
cap/static/js/cap/controllers/capCtrl.js
cap/static/templates/cap/experiments.html
scripts/init-db.sh

global: fixes state issue in general controller

---

cap/static/templates/cap/deposit/createNewDepositModal.html

deposit: fix 'create' modal links

---

cap/jsonschemas/options/deposits/records/lhcb-v0.0.1.json
cap/modules/experiments/scripts/lhcb/lhcb.py
cap/modules/experiments/static/example_lhcb/ana_titles.json
cap/modules/experiments/views/lhcb.py
cap/static/js/cap/controllers/capTypeaheadCtrl.js
cap/static/scss/forms.scss
cap/static/templates/cap_records_js/decorators/typeahead.html

LHCb: improve autofill

---

cap/static/templates/cap/components/capContentBar.html
cap/static/templates/cap/pushmenu/SubMenu.html

deposit: fixes save button

---

cap/modules/user/views.py

REST: refactors user

---

cap/jsonschemas/definitions/alice-datasets-v0.0.1.json
cap/jsonschemas/definitions/alice-main-analysis-v0.0.1.json
cap/jsonschemas/options/deposits/records/alice-analysis-v0.0.1.json
cap/modules/deposit/loaders.py
cap/modules/deposit/utils.py
tests/unit/deposit/test_utils.py

deposit: removes empty values on save

---

cap/static/js/cap/controllers/capCtrl.js
cap/static/scss/cap.scss
cap/static/templates/cap/components/capHeader.html

REST: fixes login issues

---

cap/jsonschemas/definitions/alice-datasets-v0.0.1.json
cap/jsonschemas/definitions/alice-train-analysis-v0.0.1.json
cap/jsonschemas/options/deposits/records/alice-analysis-v0.0.1.json
cap/jsonschemas/records/alice-analysis-v0.0.1.json

ALICE: schema and form fixes

---

cap/modules/deposit/permissions.py
cap/modules/deposit/search.py
cap/modules/records/permissions.py

access: fixes admin permission

---

cap/bundles.py
cap/modules/oauth2server/views/server.py
cap/modules/oauth2server/views/settings.py
cap/static/js/cap/cap.config.js
cap/static/js/cap/components/capClientForm.js
cap/static/js/cap/components/capModal.js
cap/static/js/cap/components/capTokenForm.js
cap/static/js/cap/controllers/capCtrl.js
cap/static/js/cap/controllers/capUserCtrl.js
cap/static/js/cap/services/capUserClient.js
cap/static/scss/body.scss
cap/static/scss/cap.scss
cap/static/templates/cap/components/capHeader.html
cap/static/templates/cap/profile/components/clientForm.html
cap/static/templates/cap/profile/components/tokenForm.html
cap/static/templates/cap/profile/components/tokenModal.html
cap/static/templates/cap/profile/index.html
cap/static/templates/cap/profile/profile.applications.html
cap/static/templates/cap/profile/profile.html
cap/static/templates/cap/profile/profile.overview.html
cap/static/templates/cap/profile/profile.settings.html
setup.py

account: add profile page, oauth2server features

---

cap/config.py
cap/modules/experiments/scripts/lhcb/lhcb.py
cap/modules/experiments/views/lhcb.py

LHCb: improve parsing script for Publications and WG db

---

cap/jsonschemas/deposits/common/file-grabber-v0.0.1.json
cap/mappings/deposits/records/alice-analysis-v0.0.1.json
cap/mappings/deposits/records/atlas-workflows-v0.0.1.json
cap/mappings/deposits/records/cms-analysis-v0.0.1.json
cap/mappings/deposits/records/cms-auxiliary-measurements-v0.0.1.json
cap/mappings/deposits/records/cms-questionnaire-v0.0.1.json
cap/modules/deposit/__init__.py
cap/modules/deposit/api.py
cap/modules/deposit/loaders.py
cap/modules/xrootd/__init__.py
cap/modules/xrootd/ext.py
cap/static/js/cap/cap.config.js
setup.py

data: xrootd addition

---

cap/static/js/cap/directives/cap.deposit.progressBar.js
cap/static/scss/forms.scss
cap/static/templates/cap/deposit/components/capDepositNavArray.html
cap/static/templates/cap/deposit/components/capDepositNavDefault.html
cap/static/templates/cap/deposit/components/capDepositNavItem.html
cap/static/templates/cap/deposit/components/capDepositNavObject.html
cap/static/templates/cap_records_js/decorators/default.html

* on navigation item click, collapses sibling form groups

deposit: update navigation in forms

---

cap/static/js/cap/controllers/capDepositCtrl.js
cap/static/js/cap/directives/cap.deposit.progressBar.js
cap/static/scss/cap.scss
cap/static/scss/forms.scss
cap/static/templates/cap/deposit/components/capDepositNavArray.html
cap/static/templates/cap/deposit/components/capDepositNavItem.html
cap/static/templates/cap/deposit/components/capDepositNavObject.html
cap/static/templates/cap/deposit/components/depositNav.html
cap/static/templates/cap/deposit/components/depositSidebar.html
cap/static/templates/cap_records_js/form.html

deposit: UI - add top navigation

---

cap/config.py
cap/jsonschemas/options/deposits/records/lhcb-v0.0.1.json
cap/jsonschemas/records/lhcb-v0.0.1.json
cap/modules/experiments/scripts/lhcb/lhcb.py
cap/modules/experiments/static/example_lhcb/ana_details.json
cap/modules/experiments/views/lhcb.py
cap/static/js/cap/controllers/capDepositCtrl.js
cap/static/js/cap/controllers/capFormAutofillCtrl.js
cap/static/js/cap/controllers/capTypeaheadCtrl.js
parse_publications.py

- parse publications
- connect analysis from WG and publications even if title is different (by ananote)
- autofill for working group and proponents
- fix autofill when resp from db is not a string

LHCb: autofill

---

cap/bundles.py
cap/jsonschemas/records/lhcb-v0.0.1.json
cap/static/js/cap/directives/capShowMore.js
cap/static/scss/cap.scss
cap/static/scss/forms.scss
cap/static/scss/type.scss
cap/static/scss/variables.scss
cap/static/templates/cap_records_js/decorators/array.html
cap/static/templates/cap_records_js/decorators/default.html
cap/static/templates/cap_records_js/decorators/fieldset.html
cap/static/templates/cap_records_js/decorators/formAssociateRecords.html
cap/static/templates/cap_records_js/decorators/formAutofill.html
cap/static/templates/cap_records_js/decorators/select.html
cap/static/templates/cap_records_js/decorators/tabarray.html
cap/static/templates/cap_records_js/decorators/textarea.html
cap/static/templates/cap_records_js/decorators/typeahead.html
cap/static/templates/cap_records_js/form.html

deposit: add collapsable descriptions

---

cap/modules/user/views.py

global: ping server

---

cap/jsonschemas/options/deposits/records/cms-analysis-v0.0.1.json
cap/jsonschemas/options/deposits/records/lhcb-v0.0.1.json
cap/jsonschemas/records/lhcb-v0.0.1.json
cap/static/js/cap/cap.main.js
cap/static/js/cap_deposit/schema-form.js
cap/static/scss/cap.scss
cap/static/scss/forms.scss
cap/static/templates/cap/deposit/components/capDepositNavItem.html
cap/static/templates/cap_records_js/decorators/array.html
cap/static/templates/cap_records_js/decorators/fieldset.html
cap/static/templates/cap_records_js/decorators/tabArrayTop.html
cap/static/templates/cap_records_js/decorators/tabarray.html

* adds "tabArrayTop" field
* updates "array" field to better show complex forms

deposit: update layout for 'array' fields

---

cap/jsonschemas/options/deposits/records/lhcb-v0.0.1.json
cap/jsonschemas/records/lhcb-v0.0.1.json
cap/modules/deposit/loaders.py

forms: refactors lhcb form

---

cap/modules/deposit/permissions.py
setup.py

deposit: fix typo in permissions

---

cap/bundles.py
cap/jsonschemas/options/deposits/records/lhcb-v0.0.1.json
cap/modules/experiments/views/lhcb.py
cap/static/js/cap/controllers/capFormAutofillCtrl.js
cap/static/js/cap/controllers/capTypeaheadCtrl.js
cap/static/js/cap/services/capAutofill.js
cap/static/templates/cap_records_js/decorators/formAutofill.html
cap/static/templates/cap_records_js/decorators/typeahead.html

* refactor autofill and typeheads fields
* remove autofill button (do autocompletion automatically on typing)
* add static and async typeahead fields

deposit: refactor autofill and typeahead fields

---

cap/modules/deposit/permissions.py

deposit: discover schema based on ana_type field

---

cap/modules/user/views.py
cap/static/scss/header.scss
cap/static/scss/searchbar.scss
cap/static/templates/cap/components/capHeader.html
cap/static/templates/cap/deposit/results.html
cap/static/templates/cap/experiment_intro.html
cap/static/templates/cap/shared_records.html

UI: general updates

---

cap/modules/user/views.py
setup.py

user: adds LDAP endpoints - user/egroup suggestions

---

cap/bundles.py
cap/jsonschemas/options/deposits/records/lhcb-v0.0.1.json
cap/static/js/cap/cap.main.js
cap/static/js/cap/controllers/capDynamicSelectCtrl.js
cap/static/templates/cap_records_js/decorators/capDynamicSelect.html

Signedoff-by: Pamfilos Fokianos <pamfilosf@gmail.com>

deposit: forms - adds DynamicSelect addon

---

cap/static/js/cap/controllers/capCtrl.js
cap/static/js/cap/controllers/capDepositCtrl.js
cap/static/templates/cap/deposit/components/capDepositNavArray.html
cap/static/templates/cap/deposit/components/capDepositNavItem.html

UI: scrollToTop on state change and depositNav switch

---

cap/static/scss/cap.scss
cap/static/scss/forms.scss
cap/static/scss/header.scss
cap/static/scss/pushmenu.scss
cap/static/scss/search.scss
cap/static/scss/searchbar.scss
cap/static/scss/variables.scss
cap/static/templates/cap/search/results.html
cap/static/templates/cap/search/results_page.html
cap/static/templates/cap/search/search_page.html
cap/static/templates/cap/search/searchbar.html
cap/static/templates/cap_records_js/form.html

* new colors for ui
* new searchbar and searchpage design

UI: style fixes

---

cap/modules/deposit/api.py
cap/modules/deposit/permissions.py
cap/modules/deposit/views/ui.py

api: adds validator endpoint

---

cap/jsonschemas/options/definitions/atlas-workflows-v0.0.1.json
cap/jsonschemas/options/definitions/workflow_schemas/packtivity/packtivity-schema-v0.0.1.json
cap/jsonschemas/options/definitions/workflow_schemas/yadage/scheduler/parameterselection-v0.0.1.json
cap/jsonschemas/options/definitions/workflow_schemas/yadage/stage-schema-v0.0.1.json
cap/jsonschemas/options/definitions/workflow_schemas/yadage/workflow-schema-v0.0.1.json
cap/jsonschemas/options/deposits/records/atlas-analysis-v0.0.1.json
cap/static/scss/cap.scss

ATLAS: update form definition titles

---

cap/config.py

global: disable JWT token check

---

cap/jsonschemas/options/deposits/records/alice-analysis-v0.0.1.json
cap/static/scss/pushmenu.scss
setup.py

alice: fixes style in alice analysis

---

setup.py

global: pin simplekv version

---

cap/modules/importer/__init__.py
cap/modules/importer/github_importer.py
cap/modules/importer/gitlab_importer.py
cap/modules/importer/importer.py
cap/modules/importer/test_parse_url.py
cap/modules/importer/utils.py
setup.py

Squashed and pushing #600 
Signed-off-by: Ana Trisovic <ana.trisovic@gmail.com>

importer: introduce git importers

---

setup.py

system: upgrade WTF version

---

cap/modules/deposit/permissions.py
cap/modules/deposit/utils.py
cap/modules/deposit/views/ui.py

deposit: discover schema based on $ana_type field

---

setup.py

setup: updates order

---

cap/config.py
cap/jsonschemas/options/deposits/records/cms-analysis-v0.0.1.json
cap/jsonschemas/records/cms-analysis-v0.0.1.json
cap/modules/experiments/tasks/cms.py
cap/modules/experiments/views/cms.py

CMS: fields mappings from CADI

---

cap/factory.py
tests/conftest.py
tests/integration/test_api.py

tests: create integration tests setup

---

cap.sample.env
cap/config.py
tests/conftest.py
tests/integration/test_api.py
tests/unit/deposit/test_deposit_index.py

* references #629
* fixtures for users associated with different experiments
* dont recreate db and users with every test
* fixture to generate oauth tokens to use in request headers
* tests for api/deposits GET

tests: users fixtures; api/deposits

---

cap/modules/access/permissions.py
cap/modules/deposit/search.py

deposit: fetches deposits created by user

---

cap/jsonschemas/definitions/alice-train-analysis-v0.0.1.json
cap/jsonschemas/options/deposits/records/alice-analysis-v0.0.1.json

ALICE: updates ALICE schema

---

cap/modules/records/serializers/json.py
cap/modules/records/serializers/schemas/json.py

deposit: return pid in basic serializer

---

cap/modules/deposit/api.py

deposit: fixes permissions for add/remove

---

cap/modules/repoimporter/image_importer.py
setup.py

* Closes: #638 #633
* Addresses: #589
Signed-off-by: Ana Trisovic <ana.trisovic@gmail.com>

gitlab: docker image importer

---

cap/config.py
cap/modules/records/serializers/__init__.py
cap/modules/records/serializers/json.py
setup.py

serializers: add basic json serializer for search results

---

cap/modules/repoimporter/github_importer.py
cap/modules/repoimporter/gitlab_importer.py

Signed-off-by: Ana Trisovic <ana.trisovic@gmail.com>

importer: return size of repo

---

cap/modules/repoimporter/github_importer.py
cap/modules/repoimporter/gitlab_importer.py
cap/modules/repoimporter/repo_importer.py
tests/unit/repoimporter/test_importer.py

Signed-off-by: Ana Trisovic <ana.trisovic@gmail.com>

importer: return archive URLs

---

.travis.yml
Dockerfile
cap/__init__.py
cap/config.py
cap/jsonschemas/deposits/common/file-grabber-v0.0.1.json
cap/jsonschemas/options/deposits/records/lhcb-v0.0.1.json
cap/modules/deposit/loaders.py
cap/modules/repoimporter/github_importer.py
cap/modules/repoimporter/gitlab_importer.py
cap/modules/repoimporter/repo_importer.py
docker-compose-dev.yml
setup.py
tests/conftest.py

files: updates fetching files from url

---

Dockerfile

docker: adds needed ENV_VARS to Dockerfile

---

tests/conftest.py
tests/integration/test_api.py

tests: api/deposits/<pid> DELETE

---

cap/__init__.py

system: removes 'ServerConf' warning

---

cap/config.py
cap/modules/deposit/api.py
cap/modules/deposit/errors.py
tests/conftest.py
tests/integration/test_api.py

tests: adds test for deposit when wrong schema

---

tests/integration/test_api.py

* Closes #670.
Co-authored-by: Anna Trzcinska <anna.trzcinska@cern.ch>

tests: finalises publish deposit tests

---

tests/conftest.py
tests/integration/test_api.py

test: deposit permissions

---

cap/modules/deposit/api.py
cap/modules/deposit/errors.py
cap/modules/deposit/permissions.py
cap/modules/deposit/utils.py
tests/integration/test_api.py

deposits: fix when "$schema" field is empty or erroneous

---

cap/modules/deposit/permissions.py
tests/integration/test_api.py

deposit: fix permissions - not allowed by default

---

cap/modules/deposit/loaders.py
cap/modules/deposit/utils.py
tests/unit/deposit/test_deposit_fetchers.py
tests/unit/deposit/test_deposit_minters.py
tests/unit/records/test_record_fetchers.py
tests/unit/records/test_record_minters.py

tests: adds tests for minters, fetchers

---

cap/config.py
cap/modules/experiments/tasks/cms.py
cap/modules/experiments/views/cms.py
cap/utils.py
tests/conftest.py
tests/integration/test_api.py
tests/unit/repoimporter/test_importer.py
tests/unit/repoimporter/test_parse_url.py

tests: tests for api/cms/cadi and cap utils methods

---

tests/integration/test_api.py

tests: adds test for deposit clone

---

cap/modules/user/views.py
tests/conftest.py
tests/integration/test_api.py
tests/unit/deposit/test_cap_deposit.py
tests/unit/test_cap_utils.py

tests: move tests to correct file

---

setup.py

global: updates setup

---

cap/modules/experiments/tasks/cms.py
tests/unit/deposit/test_cap_deposit.py
tests/unit/deposit/test_utils.py
tests/unit/repoimporter/test_importer.py

tests: adds missing tests for deposit api class

---

cap/modules/repoimporter/image_importer.py
tests/unit/repoimporter/test_archive_image.py

* fix image importer for skopeo
* remove unused parts

importer: fix image importer

---

docs/index.rst

Remove Status Update

---

cap/modules/oauth2server/views/settings.py

oauth2server: fix/disable scopes

---

cap/modules/deposit/loaders.py

records: fix key error on loader

---

cap/modules/user/views.py

* Run demo users fixture  (```sh /scripts/create-demo-users.sh```) 

dev: adds local login on DEBUG mode

---

cap/jsonschemas/deposits/records/lhcb-v0.0.1.json
cap/jsonschemas/options/deposits/records/lhcb-v0.0.1.json

LHCb: schema adjustments

---

cap/jsonschemas/deposits/records/lhcb-v0.0.1.json
cap/jsonschemas/records/lhcb-v0.0.1.json
setup.py
ui/src/actions/drafts.js
ui/src/components/deposit/components/DepositSidebar.js
ui/src/components/published/PublishedItem.js
ui/src/components/published/components/Default.js
ui/src/components/published/components/LhcbAnalysis.js

record: updates detail page

---

ui/src/actions/drafts.js
ui/src/components/deposit/components/DepositFileManager.js
ui/src/components/deposit/components/FileItem.js
ui/src/components/deposit/components/FileList.js
ui/src/components/deposit/form/themes/grommet/fields/capFiles.js
ui/src/components/deposit/form/themes/grommet/fields/index.js
ui/src/reducers/drafts.js

forms: introduces 'capFiles' field

---

ui/src/components/create/CreateDeposit.js
ui/src/components/deposit/form/Form.js
ui/src/components/deposit/form/themes/grommet/components/ArrayUtils.js
ui/src/components/deposit/form/themes/grommet/components/FieldHeader.js
ui/src/components/deposit/form/themes/grommet/components/FormLayer.js
ui/src/components/deposit/form/themes/grommet/components/ItemBrief.js
ui/src/components/deposit/form/themes/grommet/templates/AccordionArrayField.js
ui/src/components/deposit/form/themes/grommet/templates/AccordionObjectField.js
ui/src/components/deposit/form/themes/grommet/templates/ArrayFieldTemplate.js
ui/src/components/deposit/form/themes/grommet/templates/DefaultArrayField.js
ui/src/components/deposit/form/themes/grommet/templates/FieldTemplate.js
ui/src/components/deposit/form/themes/grommet/templates/LayerArrayField.js
ui/src/components/deposit/form/themes/grommet/templates/ObjectFieldTemplate.js
ui/src/components/deposit/form/themes/grommet/widgets/TextAreaWidget.js
ui/src/components/deposit/form/themes/grommet/widgets/index.js

form: minor ui fixes

---

ui/src/components/about/AboutPage.js
ui/src/components/create/AvailableDeposits.js
ui/src/components/create/CreateIndex.js
ui/src/components/index/IndexPage.js
ui/src/components/partials/Header.js

global: adds about page

---

cap/modules/deposit/api.py
cap/modules/repoimporter/github_importer.py
cap/modules/repoimporter/gitlab_importer.py
cap/modules/repoimporter/repo_importer.py
setup.py
ui/src/actions/drafts.js
ui/src/components/deposit/components/DepositFileManager.js
ui/src/components/deposit/form/themes/grommet/widgets/TextAreaWidget.js
ui/src/reducers/drafts.js

deposit: finalises file/repo functionality

---

cap/modules/deposit/api.py
cap/modules/reana/__init__.py
cap/modules/reana/models.py
cap/modules/reana/serializers.py
cap/modules/reana/views.py
setup.py
tests/conftest.py
tests/integration/test_api_reana.py
tests/unit/reana/test_model.py

reana: add model for reana jobs; view to return jobs

---

ui/src/components/deposit/components/DepositSidebar.js
ui/src/store/configureStore.js

ui: removes type from DepositSidebar

---

ui/src/components/published/PublishedItem.js
ui/src/components/published/components/CmsAnalysis.js

record: adds cadi info to detailed page

---

ui/src/components/about/AboutPage.js
ui/src/components/create/AvailableDeposits.js
ui/src/components/deposit/components/DepositFileManager.js
ui/src/components/deposit/components/DepositHeader.js
ui/src/components/deposit/components/DepositSidebar.js
ui/src/components/welcome/WelcomePage.js

global: update wordings

---

cap/jsonschemas/deposits/records/lhcb-v0.0.1.json
cap/jsonschemas/options/deposits/records/lhcb-v0.0.1.json
ui/src/components/deposit/form/themes/grommet/templates/AccordionArrayField.js

deposit: last updates in lhcb form

---

cap/config.py
cap/jsonschemas/definitions/cms-physics-object-v0.0.1.json
cap/jsonschemas/deposits/records/cms-analysis-v0.0.1.json
cap/mappings/v5/deposits/records/cms-analysis-v0.0.1.json
cap/mappings/v5/records/cms-analysis-v0.0.1.json
cap/modules/experiments/utils/cms.py
cap/modules/experiments/views/cms.py
ui/src/components/deposit/form/themes/grommet/widgets/TextWidget.js
ui/src/components/search/SearchResults.js

* remove facets for cuts (can be typed in searchbar instead)
* update mappings for cms datasets
* escape html characters for "from cadi db" data
* add labels in search results for particle type

search: cleanups for search

---

ui/src/components/published/PublishedItem.js
ui/src/components/published/components/AliceAnalysis.js

alice: alice detailed record

---

cap/jsonschemas/deposits/records/cms-analysis-v0.0.1.json
cap/jsonschemas/options/deposits/records/cms-analysis-v0.0.1.json
scripts/clean-and-init.sh
ui/src/components/create/CreateDeposit.js
ui/src/components/deposit/form/themes/grommet/fields/importDataField.js
ui/src/components/deposit/form/themes/grommet/widgets/SwitchWidget.js
ui/src/components/deposit/form/themes/grommet/widgets/index.js
ui/src/components/published/PublishedItem.js
ui/src/components/published/components/AliceAnalysis.js

CMS: adds dependencies for reuse mode

---

cap/jsonschemas/options/deposits/records/cms-analysis-v0.0.1.json

cms: fix urls for autosuggest datasets

---

cap/config.py
cap/modules/reana/views.py

reana: removes public token

---

ui/src/components/published/components/AliceAnalysis.js
ui/src/components/published/components/CmsAnalysis.js
ui/src/components/published/components/Default.js
ui/src/components/published/components/LhcbAnalysis.js

fixes files in published

---

cap/modules/user/views.py

permissions: fix for search permissions

---

ui/src/actions/drafts.js
ui/src/components/create/CreateDeposit.js
ui/src/components/deposit/components/DepositSidebar.js
ui/src/components/footer/Footer.js
ui/src/components/index/IndexPage.js
ui/src/components/partials/Header.js
ui/src/reducers/drafts.js

ui: adds footer

---

ui/package-lock.json
ui/src/actions/auth.js
ui/src/components/dashboard/Dashboard.js
ui/src/components/deposit/components/DepositHeader.js
ui/src/components/deposit/form/themes/grommet-preview/templates/AccordionArrayField.js
ui/src/components/deposit/form/themes/grommet-preview/templates/ArrayFieldTemplate.js
ui/src/components/deposit/form/themes/grommet-preview/templates/DefaultArrayField.js
ui/src/components/deposit/form/themes/grommet-preview/templates/FieldTemplate.js
ui/src/components/deposit/form/themes/grommet-preview/templates/LayerArrayField.js
ui/src/components/deposit/form/themes/grommet-preview/templates/ObjectFieldTemplate.js
ui/src/components/deposit/form/themes/grommet-preview/widgets/TextWidget.js
ui/src/components/deposit/form/themes/grommet/fields/index.js
ui/src/components/deposit/form/themes/grommet/templates/StringArrayField.js
ui/src/components/drafts/DraftPreview.js
ui/src/components/published/components/AliceAnalysis.js
ui/src/components/published/components/CmsAnalysis.js
ui/src/components/published/components/Default.js
ui/src/components/published/components/LhcbAnalysis.js
ui/src/components/search/SearchResults.js
ui/src/reducers/authReducer.js

UI: fixes lint errors for build

---

cap/config.py
cap/modules/fixtures/__init__.py
cap/modules/fixtures/cli.py
cap/modules/records/resolvers/local.py
cap/modules/schemas/__init__.py
cap/modules/schemas/errors.py
cap/modules/schemas/models.py
cap/modules/schemas/utils.py
setup.py
tests/unit/schemas/test_model.py
tests/unit/schemas/test_utils.py

* cap fixtures schemas - to create initial schemas from files
* resolver takes schemas from db, not from files 
* closes #823 

resolvers: schemas in db

---

cap/config.py
cap/jsonschemas/deposits/records/atlas-analysis-v0.0.1.json
cap/jsonschemas/deposits/records/lhcb-v0.0.1.json
cap/jsonschemas/options/deposits/records/atlas-analysis-v0.0.1.json
cap/jsonschemas/options/deposits/records/lhcb-v0.0.1.json
cap/jsonschemas/records/atlas-analysis-v0.0.1.json
cap/jsonschemas/records/lhcb-v0.0.1.json
cap/modules/user/views.py
tests/integration/test_user_views.py
ui/src/components/deposit/form/themes/grommet/widgets/TextWidget.js

forms: use orcid identifiers in forms; autofill using ORCID api

---

cap/jsonschemas/deposits/records/lhcb-v0.0.1.json
cap/mappings/v5/deposits/records/cms-analysis-v0.0.1.json
cap/mappings/v5/deposits/records/lhcb-v0.0.1.json
cap/mappings/v5/records/cms-analysis-v0.0.1.json
cap/mappings/v5/records/lhcb-v0.0.1.json
ui/src/styles/styles.scss

search: add mappings for LHCb form

---

ui/src/components/create/CreateDeposit.js
ui/src/components/deposit/form/themes/grommet/widgets/TextWidget.js

forms: adds spinner in orcid field

---

cap/jsonschemas/definitions/publication-v0.0.1.json
cap/jsonschemas/deposits/records/cms-analysis-v0.0.1.json
cap/jsonschemas/options/deposits/records/cms-analysis-v0.0.1.json
cap/jsonschemas/options/deposits/records/lhcb-v0.0.1.json
cap/jsonschemas/records/cms-analysis-v0.0.1.json
ui/src/components/about/HowToSearch.js
ui/src/components/deposit/form/themes/grommet/components/ItemBrief.js
ui/src/components/deposit/form/themes/grommet/templates/LayerArrayField.js

forms: string representation for objects in array

---

cap/jsonschemas/definitions/cms-physics-object-v0.0.1.json
cap/jsonschemas/deposits/records/cms-analysis-v0.0.1.json
cap/jsonschemas/deposits/records/lhcb-v0.0.1.json
cap/jsonschemas/options/deposits/records/cms-analysis-v0.0.1.json
ui/src/components/drafts/form/themes/grommet/widgets/SelectWidget.js
ui/src/styles/styles.scss

CMS: changes to cms form

---

cap/config.py
cap/modules/fixtures/utils.py

fixtures: register drafts with given pids

---

cap/config.py

global: updates allowed hosts

---

ui/src/components/drafts/form/themes/grommet/fields/CapFiles.js

ui: fix bug with file input

---

requirements-devel.txt

global: removes wdb

---

cap/modules/deposit/api.py
cap/modules/deposit/search.py
cap/modules/deposit/views/ui.py
cap/modules/records/serializers/json.py
cap/modules/records/serializers/schemas/common.py
cap/modules/records/serializers/schemas/json.py
cap/modules/user/views.py
setup.py
ui/package.json
ui/src/actions/drafts.js
ui/src/components/drafts/CreateDeposit.js
ui/src/components/drafts/components/DepositSettings.js
ui/src/components/search/SearchResults.js
ui/src/reducers/drafts.js

* Refactors ui access.
* Removes autosuggest package.
* Closes #891.

access: adds egroups from ui

---

ui/package.json
ui/src/components/drafts/components/DepositSidebar.js

deposit: removes start preserving

---

cap/modules/oauthclient/contrib/cern.py
requirements.txt
ui/src/components/drafts/components/DepositSettings.js

settings: adds debounce to query

---

cap/modules/deposit/views/ui.py
cap/modules/experiments/views/alice.py
cap/modules/experiments/views/atlas.py
cap/modules/experiments/views/lhcb.py
cap/modules/oauth2server/views/server.py
cap/modules/oauth2server/views/settings.py
cap/views.py

global: removes unused static views

---

pytest.ini
scripts/schemas.py

tests: ignore UI dirs silent PEP8 in tests

---

cap/modules/deposit/api.py

deposit: dont create links for update and patch

---

cap/__init__.py
cap/celery.py
cap/cli.py
cap/config.py
cap/factory.py
cap/wsgi.py
docker/uwsgi/uwsgi_rest.ini
docker/uwsgi/uwsgi_ui.ini
tests/conftest.py

system: disable 'strict_slashes', add custom wsgi

---

cap/__init__.py
cap/celery.py
cap/cli.py
cap/config.py
cap/factory.py
cap/modules/deposit/api.py
cap/wsgi.py
docker/uwsgi/uwsgi_rest.ini
docker/uwsgi/uwsgi_ui.ini
tests/conftest.py
tests/integration/test_update_deposit.py

* deposit: remove fields from deposit data
* system: disable 'strict_slashes', add custom wsgi
* accounts: removes confirmable, registration email

 deposit: remove fields from deposit data

---

cap/modules/deposit/api.py
tests/integration/test_publish_deposit.py
tests/integration/test_update_deposit.py

deposit: fix issue on edit, patch

---

ui/src/components/settings/SettingsIndex.js
ui/src/components/settings/utils.js

ui: fixes settings page

---

cap/modules/deposit/api.py
tests/integration/test_update_deposit.py

deposit: fix issue on deposit patch with '_files'

---

cap/modules/deposit/api.py
tests/integration/test_update_deposit.py

deposit: protect '_experiment' field on update

---

ui/src/actions/drafts.js
ui/src/components/drafts/CreateDeposit.js
ui/src/components/drafts/DraftsIndex.js
ui/src/components/drafts/components/DepositSettings.js
ui/src/reducers/drafts.js

ui: fixes permissions in user/egroup

---

cap/modules/records/serializers/json.py

deposits: fix error in serializers

---

ui/src/components/drafts/DraftEditor.js
ui/src/components/drafts/components/DraftActionsButtons.js

deposit: fixes delete action

---

ui/src/components/drafts/components/DraftActionsButtons.js
ui/src/components/drafts/form/GrommetForm.js
ui/src/components/drafts/form/themes/grommet/templates/ErrorListTemplate.js
ui/src/components/drafts/form/themes/grommet/templates/FieldTemplate.js
ui/src/components/settings/SettingsIndex.js
ui/src/components/settings/utils.js

settings: throw error when no name supplied

---

setup.py
tests/integration/test_api_reana.py
ui/src/components/published/components/AliceAnalysis.js
ui/src/components/published/components/Default.js

reana: hides rerun button and removes urls

---

ui/src/components/dashboard/Dashboard.js
ui/src/components/settings/SettingsIndex.js

logout: fixes blank page logout

---

ui/src/components/App.js
ui/src/components/about/HowToSearch.js
ui/src/components/drafts/DraftPreview.js
ui/src/components/drafts/DraftsCreateIndex.js
ui/src/components/drafts/components/DraftActionsLayer.js
ui/src/components/drafts/components/DraftHeader.js
ui/src/components/partials/Header.js
ui/src/components/search/SearchBar.js
ui/src/components/search/SearchFacets.js

search: fixes error in pagination

---

cap/config.py
cap/modules/deposit/api.py
cap/modules/deposit/search.py
cap/modules/records/search.py
cap/views.py
tests/integration/test_dashboard_view.py
tests/integration/test_user_views.py
ui/src/actions/dashboard.js
ui/src/actions/search.js
ui/src/components/App.js
ui/src/components/about/AboutPage.js
ui/src/components/about/HowToSearch.js
ui/src/components/dashboard/Dashboard.js
ui/src/components/index/IndexPage.js
ui/src/components/partials/Header.js
ui/src/components/search/SearchResults.js
ui/src/reducers/dashboard.js
ui/src/reducers/index.js
ui/src/reducers/searchReducer.js

 ui: new dashboard

---

cap/jsonschemas/deposits/records/cms-analysis-v0.0.1.json
cap/jsonschemas/deposits/records/cms-questionnaire-v0.0.1.json
cap/jsonschemas/options/deposits/records/cms-analysis-v0.0.1.json
cap/jsonschemas/options/deposits/records/cms-questionnaire-v0.0.1.json
cap/jsonschemas/records/cms-analysis-v0.0.1.json
cap/jsonschemas/records/cms-questionnaire-v0.0.1.json
cap/views.py
ui/src/components/drafts/form/themes/grommet/fields/importDataField.js
ui/src/components/partials/Header.js

cms: attach cms-questionnaire to analysis

---

ui/src/components/settings/SettingsIndex.js
ui/src/components/settings/utils.js

ui: update user/settings page

---

cap/jsonschemas/deposits/records/lhcb-v0.0.1.json
cap/jsonschemas/records/lhcb-v0.0.1.json
ui/src/actions/drafts.js
ui/src/components/App.js
ui/src/components/drafts/components/DraftDefaultHeader.js
ui/src/components/drafts/components/DraftEditorHeader.js
ui/src/components/drafts/form/themes/grommet-preview/components/FieldHeader.js
ui/src/components/drafts/form/themes/grommet/fields/importDataField.js
ui/src/components/published/PublishedPreview.js
ui/src/components/search/SearchBar.js
ui/src/components/search/SearchResults.js

ui: fixes select field in lhcb

---

ui/src/components/drafts/form/themes/grommet/templates/StringArrayField.js

ui: add trash icon to remove fields

---

cap/modules/deposit/search.py

permissions: get roles from identity

---

ui/src/components/drafts/form/themes/grommet/templates/DefaultArrayField.js

ui: add trash icon to remove accordion array fields

---

ui/src/components/drafts/form/themes/grommet/fields/importDataField.js
ui/src/components/drafts/form/themes/grommet/widgets/SelectWidget.js

ui: fix arrow on hover in select widget

---

ui/package.json
ui/src/components/drafts/form/themes/grommet/fields/importDataField.js
ui/src/components/drafts/form/themes/grommet/widgets/SelectWidget.js
ui/src/components/search/SearchBar.js
ui/src/components/search/SearchResults.js

ui: truncate abstract on search results, when too long

---

cap/jsonschemas/deposits/records/cms-questionnaire-v0.0.1.json
cap/jsonschemas/options/deposits/records/cms-questionnaire-v0.0.1.json
cap/jsonschemas/records/cms-questionnaire-v0.0.1.json
ui/src/components/drafts/form/themes/grommet/templates/ObjectFieldTemplate.js
ui/src/components/drafts/form/themes/grommet/widgets/SelectWidget.js

forms: fixes cms questionnaire form

---

ui/src/components/drafts/components/CreateDraftSidebar.js
ui/src/components/drafts/components/DraftEditorHeader.js
ui/src/components/drafts/components/DraftJSONPreviewer.js
ui/src/components/drafts/form/Form.js
ui/src/components/drafts/form/themes/grommet/widgets/TextWidget.js
ui/src/components/partials/Header.js

ui: TextWidget validation fix - add BETA banner to header

---

ui/src/components/drafts/form/Form.js

ui: forms - fix validationError in capFiles

---

cap/config.py

lhcb: set publications file location to eos

---

ui/src/actions/drafts.js
ui/src/components/drafts/DraftEditor.js
ui/src/components/drafts/DraftPreview.js
ui/src/components/drafts/components/DepositSettings.js
ui/src/components/drafts/components/DraftActionsButtons.js
ui/src/components/drafts/form/themes/grommet-preview/components/ItemBrief.js
ui/src/components/drafts/form/themes/grommet-preview/templates/FieldTemplate.js
ui/src/components/drafts/form/themes/grommet/components/ItemBrief.js
ui/src/components/drafts/form/themes/grommet/fields/importDataField.js
ui/src/components/published/PublishedPreview.js
ui/src/components/search/SearchFacets.js
ui/src/components/search/SearchResults.js

ui: clear lint errors, fix lodash imports

---

ui/src/components/about/AboutPage.js

ui: update about page

---

ui/src/actions/drafts.js
ui/src/components/drafts/components/FileItem.js
ui/src/components/drafts/components/FileList.js
ui/src/reducers/drafts.js

files: adds option to remove file

---

ui/src/components/about/HowToSearch.js

ui: lowercase how to search page

---

cap/jsonschemas/deposits/records/lhcb-v0.0.1.json
cap/jsonschemas/options/deposits/records/lhcb-v0.0.1.json
cap/jsonschemas/records/lhcb-v0.0.1.json
cap/mappings/v5/deposits/records/lhcb-v0.0.1.json
cap/mappings/v5/records/lhcb-v0.0.1.json

lhcb: fix status in schema

---

ui/src/components/drafts/components/DepositFileManager.js
ui/src/components/drafts/components/SectionHeader.js
ui/src/components/drafts/form/CleanForm.js
ui/src/components/published/PublishedPreview.js
ui/src/components/search/SearchResults.js
ui/src/components/settings/SettingsIndex.js

ui: changes title in file manager

---

cap/modules/deposit/search.py
tests/integration/test_get_deposits.py
ui/src/components/drafts/form/themes/grommet-preview/widgets/TextAreaWidget.js

* this is a temporary workaround, to show both, drafts and published on
the search page (in the future should be removed)

search: deposit search shows also published in experiment

---

cap/config.py
ui/src/actions/search.js

ui: on the search page by default sort by latest

---

docs/index.rst
docs/project.rst

Signed-off-by: Artemis Lavasa <artemis.lavasa@cern.ch>

docs: updates to readthedocs for BETA release

---

ui/src/components/about/AboutPage.js
ui/src/components/about/HowToSearch.js
ui/src/components/footer/Footer.js
ui/src/components/index/IndexPage.js
ui/src/components/partials/Header.js
ui/src/components/search/SearchBar.js

ui: fixes about/search page

---

cap/config.py
docker-compose.full.yml
docker/nginx/conf.d/default.conf
tests/conftest.py

global: enables talsiman

---

cap/modules/records/serializers/json.py
cap/modules/records/serializers/schemas/common.py
cap/modules/records/serializers/schemas/json.py
cap/modules/schemas/permissions.py
ui/src/components/search/SearchResults.js

serializers: add can-edit, can-read, can-admin

---

ui/tools/distServer.js

tools: removes browserSync from production build

---

ui/src/components/dashboard/Dashboard.js

ui: adds check for user in dashboard

---

setup.py
ui/src/components/dashboard/Dashboard.js

ui: fetches user from state in dashboard

---

ui/src/components/drafts/DraftEditor.js
ui/src/components/drafts/components/DraftEditorHeader.js
ui/src/reducers/drafts.js

ui: throws 403 in create from

---

ui/src/actions/drafts.js
ui/src/components/about/AboutPage.js
ui/src/components/drafts/components/FileItem.js
ui/src/reducers/drafts.js

ui: fetches files from api/files

---

ui/src/index.ejs

ui: removes redundant packages

---

cap/mappings/v5/deposits/records/cms-analysis-v0.0.1.json
cap/mappings/v5/records/cms-analysis-v0.0.1.json
cap/modules/fixtures/utils.py
ui/src/components/search/SearchFacets.js
ui/src/components/search/SearchResults.js

mappings: update cms-analysis mappings

---

cap/mappings/v5/deposits/records/alice-analysis-v0.0.1.json
cap/mappings/v5/deposits/records/atlas-analysis-v0.0.1.json
cap/mappings/v5/deposits/records/atlas-workflows-v0.0.1.json
cap/mappings/v5/deposits/records/cms-analysis-v0.0.1.json
cap/mappings/v5/deposits/records/cms-questionnaire-v0.0.1.json
cap/mappings/v5/deposits/records/lhcb-v0.0.1.json
cap/mappings/v5/records/atlas-analysis-v0.0.1.json
cap/mappings/v5/records/atlas-workflows-v0.0.1.json
cap/mappings/v5/records/cms-analysis-v0.0.1.json
cap/mappings/v5/records/cms-questionnaire-v0.0.1.json
cap/mappings/v5/records/lhcb-v0.0.1.json

mapping: add updated field

---

ui/src/components/dashboard/Dashboard.js

ui: fix links in the dashboard

---

cap/views.py

* for files monitoring a 'test.txt' file needs
to be added in the 'default_location'

devops: adds views to monitor db, es, files

---

cap/config.py
cap/modules/deposit/search.py
cap/modules/experiments/tasks/cms.py
cap/modules/experiments/tasks/lhcb.py
cap/modules/experiments/utils/cms.py
cap/modules/records/resolvers/local.py
setup.py

celery: install periodic tasks

---

.travis.yml
ui/src/actions/search.js
ui/src/components/drafts/DraftsIndex.js
ui/src/components/drafts/components/DraftActionsButtons.js
ui/src/components/partials/Header.js
ui/src/components/search/SearchBar.js
ui/src/components/search/SearchPage.js
ui/src/components/search/SearchResults.js
ui/src/components/search/SearchUtils.js
ui/src/components/search/components/Suggestions.js

* Adds Suggestions
* debounces pagination

ui: improves search

---

ui/src/components/partials/Header.js
ui/src/components/search/SearchBar.js
ui/src/components/search/components/Suggestions.js

ui: styling for searchbar

---

cap/config.py
cap/modules/deposit/api.py
cap/modules/deposit/permissions.py
cap/modules/deposit/search.py
cap/modules/experiments/permissions.py
cap/modules/experiments/views/cms.py
cap/modules/records/api.py
cap/modules/records/permissions.py
cap/modules/records/search.py
cap/modules/schemas/permissions.py
cap/modules/user/views.py
scripts/clean-and-init.sh
setup.py
tests/conftest.py
tests/integration/test_get_deposits.py
tests/integration/test_permissions_api.py
tests/integration/test_publish_deposit.py
tests/integration/test_update_deposit.py

* closes #1066 
* closes #1062 
* closes #1063 
* closes #983 

experiments permissions in db; add permissions for records

---

ui/src/components/drafts/components/SectionHeader.js

ui: fixes bug with overflow on firefox

---

cap/config.py
cap/modules/experiments/views/atlas.py
cap/modules/reana/views.py
setup.py

reana: re-plugs reana

---

cap/mappings/v5/deposits/records/atlas-analysis-v0.0.1.json
cap/mappings/v5/records/atlas-analysis-v0.0.1.json

mappings: disable indexing for workflows objects

---

cap/factory.py
cap/modules/access/permissions.py
cap/modules/deposit/api.py
cap/modules/deposit/utils.py
cap/modules/experiments/views/atlas.py
cap/modules/experiments/views/cms.py
cap/modules/experiments/views/lhcb.py
cap/modules/fixtures/utils.py
cap/modules/oauth2server/views/settings.py
cap/modules/oauthclient/rest_handlers.py
cap/modules/reana/views.py
cap/modules/records/api.py
cap/modules/records/serializers/json.py
cap/modules/records/serializers/schemas/common.py
cap/modules/records/utils.py
cap/modules/repoimporter/image_importer.py
cap/modules/search/query.py
cap/modules/user/views.py
run-tests.sh

global: fixes docstrings

---

cap/config.py
cap/modules/reana/errors.py
cap/modules/reana/views.py
tests/conftest.py
tests/integration/test_api_reana.py

reana: access token implementation

---

ui/src/components/published/RunsListItem.js

ui: fixes lint errors

---

cap/modules/repoimporter/gitlab_importer.py

repoimporter: updates Gitlab archive URL

---

.githooks/pre-commit
.githooks/pre-push
INSTALL.rst

* to link a hooks in your local repo use
$ git config core.hooksPath .githooks

global: add git hooks

---

INSTALL.rst
ui/package.json

docs: new install guide

---

cap/config.py
cap/modules/experiments/utils/atlas.py
cap/modules/experiments/views/atlas.py
setup.py
tests/integration/test_atlas_views.py
tests/unit/experiments/test_atlas_utils.py

atlas: autocomplete based on glance id

---

requirements.txt
ui/src/components/drafts/components/FileItem.js
ui/src/components/drafts/components/FileList.js
ui/src/components/published/PublishedItemIndex.js
ui/src/components/published/PublishedPreview.js

ui: display title/id on published detail

---

cap/jsonschemas/deposits/records/cms-analysis-v0.0.1.json
cap/jsonschemas/options/deposits/records/cms-analysis-v0.0.1.json
cap/jsonschemas/records/cms-analysis-v0.0.1.json
cap/mappings/v5/deposits/records/cms-analysis-v0.0.1.json
cap/mappings/v5/records/cms-analysis-v0.0.1.json

CMS: move triggers under primary datasets field

---

Dockerfile
ui/src/components/drafts/form/themes/grommet/fields/ServiceIDGetter.js
ui/src/components/drafts/form/themes/grommet/widgets/TextWidget.js
ui/src/components/published/PublishedPreview.js

ui: fix build errors

---

cap/config.py

CMS: update url for cadi auth

---

cap/modules/experiments/utils/common.py

* flag -p not available on machines

global: fix kinit decorator

---

tests/unit/experiments/test_common_utils.py
ui/src/components/about/HowToSearch.js
ui/src/components/footer/Footer.js
ui/src/components/partials/Header.js

ui: move search tips to header

---

setup.py

fix invenio-records-files version

---

.travis.yml
scripts/ci/prebuild.sh
scripts/helpers/check_commit_subject.sh

travis: checks commit subject validity

---

requirements.txt
setup.py

installation: pins working versions of invenio modules

---

cap/modules/deposit/api.py

deposit: update 'jsonschema' import locations

---

cap/jsonschemas/options/deposits/records/atlas-analysis-v0.0.1.json
cap/jsonschemas/options/deposits/records/lhcb-v0.0.1.json
cap/modules/user/views.py
ui/src/actions/auth.js
ui/src/components/App.js
ui/src/components/auth/AuthorizationRequired.js
ui/src/components/drafts/form/themes/grommet/widgets/TextWidget.js
ui/src/components/index/IndexPage.js
ui/src/components/welcome/WelcomePage.js

Update function for the ORCID name.
The search is initiated on Enter.

UI: initiate the ORCID search when the users press enter

---

cap/jsonschemas/definitions/ror-v0.0.1.json
cap/modules/services/serializers/ror.py
cap/modules/services/test_responses/responses.py
cap/modules/services/views/__init__.py
cap/modules/services/views/ror.py
cap/modules/services/views/status_checks.py
tests/integration/test_ror_api.py

services: ROR service endpoint and serializer

---

cap/config.py
cap/modules/deposit/ext.py
cap/modules/schemas/imp.py
cap/modules/schemas/models.py
requirements-local-forks.txt

schemas: imp for get_mappings method from invenio_search module

---

cap/modules/deposit/api.py
tests/integration/test_edit_published_deposit.py

deposits: fix access on deposit edit action

---

cap/modules/records/serializers/schemas/common.py
tests/integration/test_serializers.py

records: replace role_id with name in access serializers

---

cap/modules/records/serializers/schemas/json.py
cap/modules/schemas/models.py
cap/modules/schemas/resolvers.py
tests/integration/test_schemas_views.py
tests/unit/schemas/test_utils.py

schemas: use use_deposit_as_record flag for schemas

---

.gitignore
cap/modules/deposit/api.py
cap/modules/deposit/permissions.py
cap/modules/records/permissions.py
cap/modules/schemas/models.py
cap/modules/schemas/utils.py
cap/modules/schemas/views.py
cap/modules/user/views.py
tests/integration/test_files_workflow.py
tests/integration/test_schemas_views.py
tests/unit/schemas/test_utils.py

Rebased #1272 #1277
* deposit: unlock bucket on deposit edit
* records: fix record files permissions
* schemas: add latest flag to get method

records: unlock bucket on deposit edit

---

cap/modules/schemas/resolvers.py
tests/conftest.py

schemas: cache schema on resolve_schema_by_url method

---

cap/views.py
tests/integration/test_dashboard_view.py

global: serialize dashboard results

---

cap/config.py
cap/modules/search/query.py
cap/views.py

search: add aggregation for cms working group

---

cap/modules/fixtures/schemas/alice-analysis.json
cap/modules/fixtures/schemas/lhcb.json

schemas: update lhcb and alice schemas name to be consistent

---

ui/src/components/drafts/components/FileItem.js

ui: extra icons

---

cap/modules/fixtures/schemas/cms.json
ui/src/actions/draftItem.js
ui/src/components/dashboard/Dashboard.js
ui/src/components/drafts/DraftsItemIndex.js
ui/src/components/drafts/components/DepositSidebar.js
ui/src/components/drafts/components/DraftActionsButtons.js
ui/src/components/drafts/components/DraftActionsLayer.js
ui/src/components/drafts/components/DraftEditorHeader.js
ui/src/components/drafts/components/DraftHeader.js
ui/src/components/drafts/form/Form.js
ui/src/components/drafts/form/themes/grommet-preview/widgets/SwitchWidget.js
ui/src/components/footer/Footer.js
ui/src/components/partials/Header.js

ui: small ui fixes

---

cap/modules/records/serializers/schemas/common.py
cap/modules/workflows/utils.py
cap/views.py
tests/integration/test_create_deposit.py
tests/integration/test_dashboard_view.py
tests/integration/test_edit_published_deposit.py
tests/integration/test_get_deposits.py
tests/integration/test_get_records.py
tests/integration/test_publish_deposit.py
tests/integration/test_serializers.py
tests/integration/test_update_deposit.py
ui/src/components/dashboard/Dashboard.js
ui/src/components/dashboard/DashboardList.js
ui/src/components/drafts/DraftCreate.js
ui/src/components/drafts/components/DepositSidebar.js
ui/src/components/drafts/components/DraftIntegrations.js
ui/src/components/errors/403.js
ui/src/components/errors/404.js

ui: updates to dashboard

---

cap/modules/auth/config.py
cap/modules/auth/views.py
cap/modules/repoimporter/api.py
cap/modules/repoimporter/utils.py
tests/integration/test_git_importer.py
tests/unit/repoimporter/test_git.py

records: fix gitlab oauth

---

cap/modules/fixtures/schemas/atlas.json
cap/modules/fixtures/schemas/cms.json
ui/src/components/App.js
ui/src/components/dashboard/DashboardList.js
ui/src/components/dashboard/DashboardListItem.js
ui/src/components/drafts/form/themes/grommet/components/AnalysisReuseMode.js
ui/src/components/drafts/form/themes/grommet/templates/TabField.js

ui: change reuse mode switch

---

ui/src/components/drafts/components/DraftDefaultHeader.js
ui/src/components/published/PublishedPreview.js

ui: hide edit button on DraftPreview if user doesn't have edit rights

---

ui/package.json
ui/src/actions/files.js
ui/src/components/drafts/components/DepositFileManager.js

* fixes the upload form by providing the correct options for the users,
which differentiate the file/repo

ui: fix upload forms

---

ui/src/components/settings/Applications.js
ui/src/components/settings/Integrations.js
ui/src/components/settings/Settings.js

ui: fixes for profile settings page

---

ui/src/actions/files.js
ui/src/components/drafts/components/FileItem.js
ui/src/reducers/draftItem.js
ui/yarn.lock

ui: drafts - fix display issues in FileManager

---

cap/modules/fixtures/schemas/atlas.json
cap/modules/fixtures/schemas/cms.json
cap/views.py
ui/package.json
ui/src/actions/files.js
ui/src/components/dashboard/Dashboard.js
ui/src/components/dashboard/DashboardList.js
ui/src/components/dashboard/DashboardQuickSearch.js
ui/src/components/dashboard/DashboardWorkflowListItem.js
ui/src/components/drafts/DraftsItemIndex.js
ui/src/components/drafts/components/DepositFileManager.js
ui/src/components/drafts/components/DraftIntegrations.js
ui/src/reducers/dashboard.js
ui/src/reducers/draftItem.js

ui: rearrange dashboard elements; fixes to uiSchemas

---

cap/modules/fixtures/schemas/cms.json
ui/yarn.lock

UI update for main measurements workflows field in cms

ui: main measurements workflow ui update

---

cap/modules/fixtures/schemas/cms-physics-object.json

CMS Form 
main measurements workflows
Physics Objects
Added conditional control to the object dropdown

ui: cms physics object fields dependencies

---

cap/modules/fixtures/schemas/alice-analysis.json
cap/modules/fixtures/schemas/atlas.json
cap/modules/fixtures/schemas/cms.json

ui: uiSchemas update to fix overlap layers

---

requirements.txt

* issue with macOS catalina and older versions of asn1crpyto
(https://github.com/wbond/asn1crypto/issues/158)

global: pin asn1crypto for mac installation

---

cap/config.py
ui/src/components/search/SearchFacets.js

When the users uncheck parent checkbox, all the nested are unchecked too.  
* close #1337

ui: nested filtering improvement

---

cap/config.py

* from #c47c9973d15e966a2243a40e26af5dec2d6ccd08

global: revert changes in config file

---

tests/integration/test_github_import.py
tests/integration/test_gitlab_import.py
ui/src/components/drafts/DraftsItemIndex.js
ui/src/components/drafts/components/DepositSettings.js
ui/src/reducers/draftItem.js

* closes #1369 
Sidebar updates:
Move Delete button to the bottom
Connect Publish button 
Display latest published version

ui: sidebar updates

---

ui/src/components/footer/Footer.js

ui: update year in the footer

---

ui/src/reducers/draftItem.js

ui: drafts - init state when draftItem changes

---

ui/src/actions/draftItem.js
ui/src/components/drafts/DraftPreview.js
ui/src/components/drafts/components/DepositAccess.js
ui/src/components/drafts/components/FileItem.js
ui/src/components/settings/Applications.js

ui: toast added auto removal

---

scripts/clean-and-init.sh

global: fix order of cmds

---

cap/modules/experiments/tasks/cms.py

cms: fix issue with lxplus machine's ip

---

ui/src/components/drafts/components/EditableTitle.js

ui: clean build errors

---

cap/modules/fixtures/schemas/cms-physics-object.json

cms: fix physics objects field in schema

---

cap/modules/services/serializers/latex.py
cap/modules/services/views/__init__.py
cap/modules/services/views/latex.py
tests/integration/test_latex.py

services: add latex endpoint for paths

---

cap/modules/auth/config.py
cap/modules/auth/serializers.py
cap/modules/auth/views.py
tests/unit/auth/test_auth_services_serializers.py

services: add serializers for authentication services

---

cap/modules/experiments/utils/common.py
cap/modules/experiments/utils/das.py
cap/modules/experiments/views/cms.py
cap/modules/fixtures/schemas/cms.json
tests/integration/test_cms_api.py

search: das datatasets suggestions with wildcards

---

cap/modules/deposit/api.py
cap/modules/deposit/validators.py
cap/modules/experiments/search/cms_triggers.py
cap/modules/experiments/search/das.py
cap/modules/experiments/utils/cadi.py
cap/modules/experiments/utils/cms.py
cap/modules/experiments/utils/common.py
cap/modules/experiments/validators.py
cap/modules/experiments/views/cms.py
cap/modules/fixtures/schemas/cms.json
tests/conftest.py
tests/integration/test_cms_api.py
tests/unit/experiments/test_cadi_utils.py
ui/src/components/drafts/form/themes/grommet/widgets/TextWidget.js

add validators for DAS datasets and triggers
* closes #1381
* closes #1382
* closes #1093 

cms: validators for DAS datasets, triggers, cadi id

---

.travis.yml

global: remove coveralls

---

cap/modules/experiments/search/__init__.py

global: add missing init file in a module

---

.travis.yml
requirements-local-forks.txt
requirements.txt
setup.py

* fix for issue  https://github.com/celery/celery/issues/4867

global: pin celery versions, use fork

---

requirements-local-forks.txt

global: pin reana version because breaks everything

---

.gitignore
ui/src/components/drafts/form/themes/grommet/components/FormLayer.js
ui/src/components/drafts/form/themes/grommet/templates/LayerArrayField.js

* The delete button is separated from the function that opens the layer
* Inside the layer, the delete button will remove the item and close the layer

Array layer delete

---

cap/config.py
cap/modules/fixtures/schemas/alice-analysis.json
cap/modules/fixtures/schemas/atlas.json
cap/modules/fixtures/schemas/cms-questionnaire.json
cap/modules/fixtures/schemas/cms.json
cap/modules/fixtures/schemas/lhcb.json
cap/modules/schemas/models.py
cap/modules/search/query.py
requirements.txt
tests/integration/test_schemas_views.py
tests/unit/schemas/test_model.py
tests/unit/schemas/test_utils.py
ui/src/components/about/HowToSearch.js

* lowercase and whitespace analyzer on query
* escape /,+,-,^ by default
* add custom analyzer for _all query
* update search tips for users
* add option to specify settings in schema mappings
* closes #1383 

search: improve searchbar queries

---

cap/modules/fixtures/schemas/cms.json
ui/src/components/drafts/form/themes/grommet/templates/AccordionObjectField.js
ui/src/components/drafts/form/themes/grommet/templates/ArrayFieldTemplate.js
ui/src/components/partials/Header.js

* accepts size and dispay props

ui: update form fields

---

cap/config.py
cap/modules/experiments/utils/cadi.py
cap/modules/user/utils.py
tests/unit/experiments/test_cadi_utils.py

* for contact person (if can be found in ldap)
* for conveners egroups
* closes #1412

cms: admin access to cadi entries

---

cap/modules/fixtures/schemas/cms.json

Update the widget for the conclusion field from text to textarea

ui: convert basic_info>conclusion to textarea

---

ui/src/components/about/HowToSearch.js

search: update search tips

---

ui/src/components/drafts/form/CleanForm.js
ui/src/components/drafts/form/themes/grommet/templates/ArrayFieldTemplate.js

ui: fix form fields width

---

cap/modules/experiments/utils/cadi.py

search: fix search by cadi id method

---

ui/webpack.config.prod.js

ui: updates webpack.prod svg config

---

cap/config.py
cap/modules/fixtures/schemas/cms.json
ui/src/components/dashboard/Dashboard.js
ui/src/components/dashboard/DashboardList.js
ui/src/components/dashboard/DashboardListItem.js
ui/src/components/dashboard/DashboardQuickSearch.js
ui/src/components/dashboard/components/DashboardMeter.js

ui: small dashboard fixes

---

tests/unit/experiments/test_cadi_utils.py
ui/src/components/about/CustomTile.js
ui/src/components/about/HowToSearch.js
ui/src/components/dashboard/Dashboard.js
ui/src/components/dashboard/DashboardListItem.js
ui/src/components/dashboard/DashboardQuickSearch.js
ui/src/components/drafts/components/DepositAccess.js
ui/src/components/drafts/components/DepositSidebar.js
ui/src/components/welcome/Intro.js

* fix loading spinner on dashboard
* fix ui problem with removing egroup permissions
* fix typo on homepage
* fix working group link on quick search

ui: small ui fixes and remove permission for egroup

---

ui/src/components/drafts/form/themes/grommet/fields/PasteArrayField.js
ui/src/components/drafts/form/themes/grommet/widgets/TextWidget.js

Fixes:
- 'x' doesn't clear input
- remove loading on creation of select input
- debounce suggestion loading on inputChange
- cleans import list on pasteImport

ui: form - fix small issues in select component

---

cap/modules/repoimporter/utils.py

services: missing /api in url for webhooks in prod

---

cap/modules/repoimporter/github_api.py
cap/modules/repoimporter/gitlab_api.py
cap/modules/services/views/latex.py
tests/integration/test_latex.py
ui/package.json
ui/src/components/drafts/components/DepositAccess.js
ui/src/components/drafts/components/DepositSettings.js
ui/src/components/drafts/components/DraftIntegrations.js
ui/src/components/drafts/components/FileTree/index.js
ui/src/components/drafts/form/themes/grommet/fields/RepoField.js
ui/src/components/latex/latex.js
ui/src/components/welcome/Intro.js

- repoField: display branch if available
- fileTree: hide 'repositories' from "all files"
- fixes backend issue when branch doesn't exist

ui: share tab, repoField, fileTree, GitHub_api fix

---

cap/modules/services/views/latex.py
tests/integration/test_latex.py
ui/package.json
ui/src/components/drafts/components/DepositAccess.js
ui/src/components/drafts/components/DepositSettings.js
ui/src/components/drafts/components/DraftIntegrations.js
ui/src/components/latex/latex.js
ui/src/components/welcome/Intro.js

ui: share tab, latex layer

---

cap/modules/repoimporter/factory.py

services: temp fix for gitlab cern factory

---

ui/src/components/drafts/components/DraftIntegrations.js
ui/src/components/drafts/components/FileTree/index.js

ui: fixes small display in repo, files

---

cap/modules/fixtures/schemas/alice-analysis.json
ui/yarn.lock

* Add basic_info object
* Add description field
* update accordion to default
* tabview

ui: alice form updates

---

cap/modules/fixtures/schemas/lhcb.json

* Create TabView
* Remove redundant array layers
* Remove redundant accordions

ui: lhcb form fields updates

---

ui/src/components/search/SearchFacets.js

ui: show `created by me` as a filter option

---

cap/modules/services/views/latex.py
tests/integration/test_latex.py

tests: fix latex test after changes

---

cap/modules/services/serializers/cds.py
cap/modules/services/views/__init__.py
cap/modules/services/views/cds.py
tests/integration/test_cds_api.py

services: add CDS integration

---

ui/src/actions/draftItem.js

ui: error toast for providing permissions to non-existing user

---

cap/modules/auth/views.py
ui/src/actions/auth.js
ui/src/components/settings/Integrations.js

* implements the backend disconnect
* adds UI functionality
* closes #1502
* closes #1503

auth: disconnect from integration option

---

cap/modules/fixtures/schemas/atlas.json
cap/modules/fixtures/schemas/cms.json
ui/src/components/drafts/form/themes/grommet/templates/FieldTemplate.js
ui/src/components/drafts/form/themes/grommet/templates/TabField.js
ui/src/components/drafts/form/themes/grommet/widgets/ReadOnlyText.js
ui/src/components/drafts/form/themes/grommet/widgets/TextWidget.js

* Update the default value when the field is readonly
* Publications to be default array
* Hide likelihoods
* Add email address format and rephrase
This PR is solving the list from the #1425 

ui: atlas form updates

---

ui/src/actions/files.js
ui/src/components/drafts/DraftPreview.js
ui/src/components/drafts/components/DepositSidebar.js
ui/src/components/drafts/components/FileItem.js

ui: draftItem error handler

---

ui/src/actions/draftItem.js
ui/src/components/drafts/components/DepositAccess.js
ui/src/components/drafts/components/DepositSettings.js
ui/src/components/drafts/components/DraftWorkflows.js
ui/src/reducers/draftItem.js

ui: update to the handlepermission function

---

cap/modules/experiments/search/cms_triggers.py
cap/modules/experiments/views/cms.py
tests/conftest.py
tests/integration/test_cms_api.py

search: improve trigger results, show distinct values

---

ui/src/actions/search.js
ui/src/components/search/SearchFacets.js
ui/src/components/search/ShowMore/ShowMore.js
ui/src/components/search/ShowMore/index.js
ui/src/reducers/searchReducer.js

Create a new HOC component for handling the number of the items presented.
Set ```limit``` to a number to define the minimum number of displayed items
Set  ```items``` the list you want to display.
If the length of the list is smaller than the limit then the list will not have a button.
Otherwise the button will toggle between the two states: 
* show the limited list
* show the whole list
It is set as WIP since the functionality is there but a minor ui bug exists.
When the user applies a filter then the whole component is re rendered and the whole list is not visible

Show more filters

---

cap/modules/deposit/serializers/json.py
cap/modules/deposit/serializers/schemas/json.py
requirements-local-forks.txt
scripts/helpers/check_commit_subject.sh

deposit: bring back can_admin to serializer

---

cap/modules/deposit/serializers/schemas/json.py

repos: remove unused serializer

---

ui/src/components/drafts/components/DepositAccess.js

ui: change permissions only when canAdmin flag is true

---

ui/src/components/drafts/components/DraftIntegrations.js

ui: remove add repos in absence of permissions

---

cap/modules/deposit/serializers/json.py
cap/modules/deposit/serializers/schemas/json.py

deposits: optimize serializer calls to db

---

cap/config.py
cap/modules/records/serializers/__init__.py
cap/modules/records/serializers/schemas/json.py
tests/integration/test_serializers.py

repos: add schema for repositories for the cap-client

---

ui/src/components/drafts/components/EditableTitle.js

* Get  ``` can_update``` from the state
* If the user has no permission to update, then the title will not be editable

ui: prevent users to update the title if they do not have permissions

---

cap/modules/experiments/utils/cadi.py

* fixes #1543
** WARNING ** cadi harvesting method needs fixes in general, as doesnt take care of all the cases

cms: fix for cadi harvester

---

scripts/create-demo-users.sh
ui/src/components/dashboard/Dashboard.js
ui/src/components/partials/Header.js

The check for the permissions will take place one level up, in order to avoid access to other resources

User without permissions

---

.travis.yml
requirements.txt

global: pins 'markupsafe' version, due to 'setuptools' update

---

ui/src/components/drafts/components/FileItem.js
ui/src/components/drafts/components/FileTree/index.js
ui/src/components/partials/HorizontalWithText.js
ui/src/components/published/PublishedPreview.js

* Update the FileList to FileTree in the published
* Edit button uses canUpdate in order to decide whether to show or not

ui: published change file list to file tree

---

ui/src/components/drafts/components/DraftIntegrations.js

ui: fix webhook getter

---

cap/modules/schemas/resolvers.py
tests/conftest.py
tests/integration/test_get_deposits.py
tests/integration/test_get_records.py
tests/integration/test_resolvers.py

schemas: dont validate permissions in resolver

---

ui/src/components/drafts/components/DraftIntegrations.js

ui: fix integrations tab after serializers change

---

cap/modules/repos/serializers.py

repos: fix github release payload serializer

---

tests/unit/repos/test_git_serializers.py

repos: add test for `GitWebhookSubscriberSchema`

---

ui/src/components/drafts/components/DepositSettings.js

* Disable the publish button when no permissions
* Display tooltip message
* closes #1554 

ui: publish button disabled when no permissions

---

ui/src/components/drafts/components/FileItem.js

ui: responsive file item

---

ui/src/components/drafts/components/DepositSidebar.js

ui: responsive sidebar info

---

ui/src/components/drafts/DraftsItemIndex.js

ui: draftItem - fix when PID does not exist

---

cap/modules/records/serializers/schemas/json.py
tests/integration/test_get_deposits.py
tests/unit/repos/test_git_serializers.py

* fixes issue in git serializer test
* closes #1587

deposits: add latest published pid to `BasicDepositSchema`

---

cap/modules/records/utils.py
cap/modules/schemas/models.py

schemas: fix version regex

---

ui/src/components/drafts/components/DepositFileManager/DropzoneUploader.js
ui/src/components/drafts/components/DepositFileManager/FileUploadProgressItem.js

* responsive upload layer for files
* Should investigate more how to customize the Layer window 

ui: file uploader responsive

---

ui/src/components/drafts/components/DraftDefaultHeader.js
ui/src/components/drafts/components/EditableTitle.js
ui/src/styles/styles.scss

* Drafts Default Header
* Editable Title

ui: default draft header responsive

---

ui/src/components/drafts/DraftsItemIndex.js
ui/src/components/drafts/components/DepositSidebar.js
ui/src/components/drafts/form/themes/grommet/templates/TabField.js
ui/src/styles/styles.scss

ui: Responsive Draft Edit view

---

ui/src/actions/draftItem.js
ui/src/actions/tests/draftItem.test.js
ui/src/reducers/draftItem.js

* closes #1580 
* update the general title update
* write tests about the process of `patchGeneralTitle`

ui: general title update improved

---

cap/modules/user/utils.py
tests/integration/test_permissions_api.py
tests/unit/deposit/test_cap_deposit.py

global: global: fix permissions issue for uppercase/lowercase

---

cap/config.py
cap/modules/experiments/utils/cadi.py
tests/conftest.py
tests/unit/experiments/test_cadi_utils.py

cms: fix error handling for cadi harvester; add logs

---

cap/modules/records/serializers/__init__.py
cap/modules/records/serializers/json.py
cap/modules/records/serializers/schemas/json.py
tests/integration/test_get_deposits.py
tests/integration/test_serializers.py
tests/unit/experiments/test_cadi_utils.py

deposit: change role id to role name in permissions serializer

---

cap/config.py
requirements-local-forks.txt
requirements.txt
setup.py

* bump invenio-logging to v1.2.0 with fork

global: enable sentry - bump invenio-logging

---

.travis.yml
cap/config.py
run-tests.sh
ui/src/actions/schemaWizard.js
ui/src/actions/tests/draftItem.test.js
ui/src/components/drafts/components/DraftEditorHeader.js
ui/src/components/drafts/components/tests/DraftEditorHeader.test.js
ui/src/components/drafts/form/themes/grommet/templates/FieldTemplate.js
ui/src/components/search/ShowMore/ShowMore.js

tests: adds UI tests on Travis CI

---

cap/modules/fixtures/schemas/cms.json
ui/package.json
ui/src/components/drafts/form/Form.js
ui/src/components/drafts/form/themes/grommet/widgets/RegExInput.js
ui/src/components/drafts/form/themes/grommet/widgets/TextWidget.js
ui/src/components/drafts/form/themes/grommet/widgets/components/InputWithButton.js
ui/src/styles/styles.scss
ui/yarn.lock

ui: introduce regex for the pattern input

---

ui/src/components/drafts/form/themes/grommet/widgets/RegExInput.js

ui: clean lint errors

---

ui/src/actions/draftItem.js
ui/src/components/drafts/DraftCreate.js

ui: update and error handling of the create analysis form

---

ui/src/reducers/draftItem.js
ui/src/reducers/tests/draftItem.test.js

* Add reducer tests for the `Edit General Title` action

tests: add test for draftItem reducer (edit title)

---

ui/src/reducers/tests/draftItem.test.js

tests: remove unused test cases

---

cap/modules/fixtures/schemas/cms.json

schemas: reorder the tabfield for cms

---

ui/cap-react/src/components/welcome/Header.js

ui: redirect to previous path  for oath login

---

cap/modules/fixtures/schemas/cms.json
ui/cap-react/src/components/drafts/form/themes/grommet/fields/CapFiles.js

ui: cms schema updates for final results

---

cap/modules/records/serializers/schemas/json.py
tests/integration/test_get_deposits.py

permissions: simplify serializer

---

cap/modules/experiments/views/cms.py
tests/integration/test_cms_api.py

cms: fix error response on CADI endpoint

---

cap/alembic/637a2a528700_change_external_id_in_gitwebhook_from_.py
docs/book.json

docs: updates theme with CAP one + alembic: updates recipe for web hook external_id

---

cap/modules/fixtures/schemas/cms.json
ui/cap-react/src/components/dashboard/Dashboard.js
ui/cap-react/src/components/dashboard/DashboardList.js
ui/cap-react/src/components/dashboard/DashboardListItem.js
ui/cap-react/src/components/dashboard/DashboardQuickSearch.js
ui/cap-react/src/components/dashboard/components/DashboardMeter.js
ui/cap-react/src/components/drafts/components/DepositFileManager/DropzoneUploader.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/ObjectFieldTemplate.js
ui/cap-react/src/index.ejs
ui/cap-react/src/styles/styles.scss

ui: fix layer overlaps

---

ui/cap-react/src/components/dashboard/Dashboard.js
ui/cap-react/src/components/dashboard/DashboardList.js
ui/cap-react/src/components/dashboard/DashboardListItem.js
ui/cap-react/src/components/dashboard/DashboardQuickSearch.js
ui/cap-react/src/components/dashboard/components/DashboardMeter.js
ui/cap-react/src/index.ejs
ui/cap-react/src/styles/styles.scss

ui: dashboard-update

---

ui/cap-react/src/components/drafts/DraftsItemNav.js
ui/cap-react/src/components/drafts/components/DraftDefaultHeader.js

ui: fix multiple requests for draft page

---

cap/modules/repos/errors.py
cap/modules/repos/utils.py
tests/unit/repos/test_git_url_parser.py

* handles PRs and tags/releases

repos: update regex to handle more options

---

ui/cap-react/src/components/drafts/form/themes/grommet/templates/ErrorFieldIndicator.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/TabField.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/stories/TabField.stories.js

ui: hidden field tab update

---

ui/cap-react/src/components/welcome/Documentation.js

ui: update links for new docs

---

docs/book.json

docs: update header nav links

---

ui/cap-react/src/components/drafts/form/themes/grommet/widgets/RegExInput.js
ui/cap-react/src/components/drafts/form/themes/grommet/widgets/TextWidget.js
ui/cap-react/src/components/drafts/form/themes/grommet/widgets/components/InputWithButton.js

- move the onFocus and the onBlur handle to `RxInputBase`
* closes #1620

ui: update onBlur and onFocus for RegExInput

---

ui/cap-react/src/components/dashboard/DashboardQuickSearch.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/FieldTemplate.js
ui/cap-react/src/components/welcome/Footer.js
ui/cap-react/src/styles/styles.scss

* closes #1668 
* closes #1669

ui: dev updates

---

cap/config.py
cap/modules/experiments/cli.py
cap/modules/experiments/utils/cms.py
cap/modules/fixtures/schemas/cms.json
requirements.txt
ui/cap-react/src/components/drafts/form/themes/grommet/widgets/SelectWidget.js

* works for schema with 'type: "array"', with 'uniqueItems: true and
type: "string" items with enum

ui: forms - updates 'SelectWidget'

---

cap/config.py
cap/modules/experiments/cli.py
cap/modules/experiments/utils/cms.py
cap/modules/fixtures/schemas/cms.json
requirements.txt

cms: keywords integration

---

ui/cap-react/src/components/StyledComponents.js
ui/cap-react/src/components/dashboard/Dashboard.js
ui/cap-react/src/components/dashboard/DashboardList.js
ui/cap-react/src/components/drafts/components/DepositSidebar.js
ui/cap-react/src/components/partials/Tag.js
ui/cap-react/src/components/published/PublishedPreview.js
ui/cap-react/src/components/search/SearchResults.js

ui: DashboardList filters updated from mine to yours

---

ui/cap-react/src/components/drafts/form/Form.js
ui/cap-react/src/components/drafts/form/themes/grommet/components/AnalysisReuseMode.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/ObjectFieldTemplate.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/TabField.js
ui/cap-react/src/styles/styles.scss

ui: select menu in the tab field, and overflow fixes

---

ui/cap-react/src/components/drafts/form/themes/grommet/fields/RepoField/RepoAction.js
ui/cap-react/src/components/drafts/form/themes/grommet/fields/RepoField/RepoActions.js
ui/cap-react/src/components/drafts/form/themes/grommet/fields/RepoField/index.js
ui/cap-react/src/components/partials/EditableField.js

ui: RepoUpload remove warnings, create renderRepoAction component

---

cap/modules/experiments/utils/das.py
cap/modules/experiments/views/cms.py
cap/modules/fixtures/schemas/cms.json
tests/conftest.py
tests/integration/test_cms_api.py

* differentiates between primary/mc datasets
* adds conditions for each type depending on suffix (AOD, SIM, etc)
* adds option for returning the full list of results
* closes #1488
* closes #1597

cms: improve dataset queries

---

cap/modules/auth/config.py

repos: enable org authorization for GitHub

---

cap/modules/fixtures/schemas/cms.json
ui/cap-react/package.json
ui/cap-react/src/components/drafts/DraftCreate.js
ui/cap-react/src/components/drafts/DraftsItemIndex.js
ui/cap-react/src/components/drafts/components/DepositFileManager/DropzoneUploader.js
ui/cap-react/src/components/drafts/form/themes/grommet/components/FieldHeader.js
ui/cap-react/src/components/drafts/form/themes/grommet/components/ImportLayer.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/ArrayFieldTemplate.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/LayerArrayField.js
ui/cap-react/src/styles/styles.scss
ui/yarn.lock

* closes #1710
- previous
- current

ui: Create Draft Button, ui update to match the platform styles

---

cap/modules/fixtures/schemas/cms.json
ui/cap-react/package.json
ui/cap-react/src/components/drafts/DraftCreate.js
ui/cap-react/src/components/drafts/DraftsItemIndex.js
ui/cap-react/src/components/drafts/components/DepositFileManager/DropzoneUploader.js
ui/cap-react/src/components/drafts/form/themes/grommet/components/FieldHeader.js
ui/cap-react/src/components/drafts/form/themes/grommet/components/ImportLayer.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/ArrayFieldTemplate.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/LayerArrayField.js
ui/cap-react/src/components/search/SearchFacetLoading/SearchFacetLoading.js
ui/cap-react/src/styles/styles.scss
ui/yarn.lock

- fix inconsistencies for the loading components
* closes #1691

ui: Search Facets loading updates

---

cap/modules/experiments/views/cms.py
cap/utils.py
setup.py
tests/integration/test_cms_api.py

cms: fix 500 on dataset queries when no query arg

---

ui/cap-react/src/components/drafts/components/DepositSidebar.js
ui/cap-react/src/components/drafts/form/themes/grommet/widgets/CheckboxWidget.js
ui/cap-react/src/components/drafts/form/themes/grommet/widgets/RadioWidget.js

ui: Remove warnings

---

cap/modules/records/utils.py
ui/cap-react/src/actions/draftItem.js
ui/cap-react/src/actions/tests/draftItem.test.js
ui/cap-react/src/reducers/draftItem.js
ui/cap-react/src/reducers/tests/draftItem.test.js

tests: add draft item tests for create and publish drafts

---

ui/cap-react/src/components/RouteGuard/RouteGuardModal.js
ui/cap-react/src/components/drafts/DraftCreate.js
ui/cap-react/src/components/drafts/components/DepositFileManager/DropzoneUploader.js
ui/cap-react/src/components/drafts/components/SectionHeader.js
ui/cap-react/src/components/drafts/form/themes/grommet/components/ImportLayer.js
ui/cap-react/src/components/partials/Button.js

* Create Button Component to introduce the same style for the platform
* closes #1716 
Styles

ui: Button component

---

ui/cap-react/src/components/search/SearchFacets.js
ui/cap-react/src/styles/styles.scss

ui: Switch Widget UI updates

---

ui/cap-react/src/components/drafts/components/DepositSettings.js

ui: Disable Publish button when is not allowed

---

ui/cap-react/src/components/welcome/Footer.js

ui: Update links for twitter and github

---

ui/cap-react/src/components/App.js
ui/cap-react/src/components/about/AboutPage.js
ui/cap-react/src/components/cms/components/CMSIndex/createModelForm.js
ui/cap-react/src/components/drafts/DraftEditor.js
ui/cap-react/src/components/drafts/components/CreateForm/CreateForm.js
ui/cap-react/src/components/drafts/components/DraftActionsLayer.js
ui/cap-react/src/components/drafts/form/themes/grommet/fields/RepoField/RepoActions.js
ui/cap-react/src/components/drafts/form/themes/grommet/fields/RepoField/index.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/AccordionArrayField.js
ui/cap-react/src/components/errors/403.js
ui/cap-react/src/components/errors/404.js
ui/cap-react/src/components/footer/Footer.js
ui/cap-react/src/components/partials/Notification.js
ui/cap-react/src/components/policy/Policy.js
ui/cap-react/src/components/policy/index.js
ui/cap-react/src/styles/styles.scss

* closes #1731 
Grouped in order to batch merge
* closes #1761 
* closes #1759 
* closes #1756 
* closes #1753 
* closes #1748

ui: Replace empty message for the AccordionArrayField

---

cap/config.py
ui/cap-react/package.json
ui/cap-react/src/actions/search.js
ui/cap-react/src/components/App.js
ui/cap-react/src/components/about/AboutPage.js
ui/cap-react/src/components/cms/index.js
ui/cap-react/src/components/drafts/DraftsItemIndex.js
ui/cap-react/src/components/drafts/DraftsRouteGuard.js
ui/cap-react/src/components/index/IndexPage.js
ui/cap-react/src/components/partials/Title.js
ui/cap-react/src/components/policy/Policy.js
ui/cap-react/src/components/published/PublishedItemIndex.js
ui/cap-react/src/components/search/SearchBar.js
ui/cap-react/src/components/search/SearchFacets.js
ui/cap-react/src/components/search/SearchPage.js
ui/cap-react/src/components/search/SearchTag/SearchTag.js
ui/cap-react/src/components/search/SearchTag/Tag.js
ui/cap-react/src/components/settings/index.js
ui/cap-react/src/components/status/StatusPage.js
ui/cap-react/tools/srcServer.js
ui/yarn.lock

* closes #1775, closes #1747, closes #1769

ui: search, document title, draftItem state updates

---

cap/config.py
cap/modules/experiments/cli.py
cap/modules/experiments/utils/questionnaire.py
cap/modules/fixtures/schemas/cms-questionnaire.json
cap/modules/records/serializers/schemas/common.py
tests/integration/test_get_deposits.py
ui/cap-react/src/components/about/HowToSearch.js
ui/cap-react/src/components/drafts/DraftPreview.js
ui/cap-react/src/components/drafts/form/JSONSchemaPreviewer.js
ui/cap-react/src/components/published/PublishedPreview.js

cms: updated questionnaire schema and UI

---

ui/cap-react/src/components/drafts/DraftCreate.js
ui/cap-react/src/components/drafts/components/DepositFileManager/FileManager.js
ui/cap-react/src/components/drafts/components/DepositFileManager/index.js
ui/cap-react/src/components/search/SearchFilterLayer/SearchFilterLayer.js
ui/cap-react/src/components/settings/Applications.js
ui/forms-playground/src/index.js

ui: fix layer issue by react-redux

---

cap/modules/deposit/api.py
cap/modules/experiments/cli.py
cap/modules/fixtures/schemas/cms-questionnaire.json

* fixes issue with permission when importing legacy Stat Questionnaires

cms: fix issue in 'cms questionnaire' CLI script 

---

cap/config.py
cap/modules/experiments/serializers.py
cap/modules/experiments/utils/cadi.py
tests/integration/test_cms_api.py
tests/unit/experiments/test_cadi_utils.py

cms: update CMS CADI info

---

ui/cap-react/src/components/drafts/DraftPreview.js
ui/cap-react/src/components/drafts/form/JSONSchemaPreviewer.js

ui: published - YAML bug on missing general_title

---

cap/modules/fixtures/schemas/cms.json

cms: update mapping for new CADI info

---

cap/config.py
cap/modules/mail/utils.py

* sends mail to PDF forum if enabled

cms: quastionnaire mail update

---

ui/cap-react/src/actions/draftItem.js
ui/cap-react/src/components/dashboard/DashboardList.js
ui/cap-react/src/components/dashboard/DashboardListItem.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/DefaultArrayField.js
ui/cap-react/src/styles/styles.scss

* closes #1813
* closes #1809 
* closes #1810

ui: makes "DashboardListItem" link, updates draft delete handling for ES

---

cap/modules/deposit/serializers/json.py
cap/modules/records/serializers/json.py
cap/modules/records/utils.py
tests/integration/test_get_deposits.py
tests/integration/test_get_records.py

search: update result links

---

ui/cap-react/src/components/drafts/DraftPreview.js
ui/cap-react/src/components/drafts/form/JSONSchemaPreviewer.js
ui/cap-react/src/components/drafts/form/themes/grommet-preview/components/FieldHeader.js
ui/cap-react/src/components/drafts/form/themes/grommet-preview/fields/capFiles.js
ui/cap-react/src/components/drafts/form/themes/grommet-preview/templates/FieldTemplate.js
ui/cap-react/src/components/drafts/form/themes/grommet-preview/templates/ObjectFieldTemplate.js
ui/cap-react/src/components/drafts/form/themes/grommet-preview/widgets/RadioWidget.js
ui/cap-react/src/components/drafts/form/themes/grommet-preview/widgets/SelectWidget.js
ui/cap-react/src/components/drafts/form/themes/grommet-preview/widgets/TextWidget.js
ui/cap-react/src/components/drafts/form/themes/grommet/components/FieldHeader.js
ui/cap-react/src/components/drafts/form/themes/grommet/components/FormLayer.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/AccordionArrayField.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/ArrayFieldTemplate.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/DefaultArrayField.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/FieldTemplate.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/LayerArrayField.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/ObjectFieldTemplate.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/StringArrayField.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/TabField.js
ui/cap-react/src/components/drafts/form/themes/grommet/widgets/SelectWidget.js
ui/cap-react/src/components/partials/FormHeader.js
ui/cap-react/src/components/partials/Tag.js
ui/cap-react/src/components/published/PublishedPreview.js
ui/cap-react/src/styles/styles.scss

ui: Preview Updates

---

ui/cap-react/src/components/RouteGuard/RouteGuard.js
ui/cap-react/src/components/RouteGuard/RouteGuardModal.js
ui/cap-react/src/components/dashboard/Dashboard.js
ui/cap-react/src/components/drafts/DraftsRouteGuard.js
ui/cap-react/src/components/drafts/components/CreateForm/CreateForm.js
ui/cap-react/src/components/drafts/components/DraftActionsLayer.js

ui: RouteGuard update

---

cap/modules/deposit/ext.py
cap/modules/deposit/utils.py
tests/integration/test_files_for_deposit.py

files: fixes links in buckets, files, and file versions

---

ui/cap-react/src/components/cms/components/CMSIndex/createModelForm.js
ui/cap-react/src/components/drafts/DraftCreate.js
ui/cap-react/src/components/drafts/DraftsItemNav.js
ui/cap-react/src/components/drafts/components/CreateForm/CreateForm.js
ui/cap-react/src/components/drafts/components/DepositAccess.js
ui/cap-react/src/components/drafts/components/DepositSidebar.js
ui/cap-react/src/components/drafts/components/DraftActionsLayer.js
ui/cap-react/src/components/drafts/components/SectionHeader.js
ui/cap-react/src/components/drafts/form/JSONSchemaPreviewer.js
ui/cap-react/src/components/drafts/form/themes/grommet-preview/components/ArrayUtils.js
ui/cap-react/src/components/drafts/form/themes/grommet-preview/components/FormLayer.js
ui/cap-react/src/components/drafts/form/themes/grommet/components/ArrayUtils.js
ui/cap-react/src/components/drafts/form/themes/grommet/components/FormLayer.js
ui/cap-react/src/components/drafts/form/themes/grommet/components/ImportLayer.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/AccordionArrayField.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/ArrayFieldTemplate.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/StringArrayField.js
ui/cap-react/src/components/latex/latex.js
ui/cap-react/src/components/partials/Button.js
ui/cap-react/src/components/search/SearchPage.js
ui/cap-react/src/components/search/SearchUtils.js
ui/cap-react/src/components/settings/Applications.js
ui/cap-react/src/styles/styles.scss

* closes #1812 
* closes #1733 
* closes #1727

Button all

---

ui/cap-react/src/components/RouteGuard/RouteGuardModal.js
ui/cap-react/src/components/about/HowToSearch.js
ui/cap-react/src/components/drafts/DraftCreate.js
ui/cap-react/src/components/drafts/components/CreateForm/CreateForm.js
ui/cap-react/src/components/drafts/components/DepositFileManager/DropzoneUploader.js
ui/cap-react/src/components/drafts/components/DepositFileManager/FileManager.js
ui/cap-react/src/components/drafts/components/DepositFileManager/index.js
ui/cap-react/src/components/drafts/components/DepositReviewCreateLayer.js
ui/cap-react/src/components/drafts/components/DepositReviews.js
ui/cap-react/src/components/drafts/components/DraftActionsLayer.js
ui/cap-react/src/components/drafts/components/FileItem.js
ui/cap-react/src/components/drafts/form/themes/grommet/components/FormLayer.js
ui/cap-react/src/components/drafts/form/themes/grommet/components/ImportLayer.js
ui/cap-react/src/components/latex/latex.js
ui/cap-react/src/components/partials/Header.js
ui/cap-react/src/components/partials/Modal.js
ui/cap-react/src/components/partials/tests/Modal.test.js
ui/cap-react/src/components/partials/tests/__snapshots__/Modal.test.js.snap
ui/cap-react/src/components/search/SearchFilterLayer/SearchFilterLayer.js
ui/cap-react/src/components/settings/Applications.js
ui/cap-react/src/styles/styles.scss

ui: Introduce Modal Component, remove the grommet one

---

ui/cap-react/src/components/drafts/form/JSONSchemaPreviewer.js

ui: disable tabview when root property not an object

---

setup.py

tests: pin `pytest-invenio`

---

ui/cap-react/src/components/partials/Modal.js

ui: fix Modal build issues

---

ui/cap-react/src/components/drafts/DraftsItemIndex.js
ui/cap-react/src/components/drafts/components/DepositFileManager/index.js
ui/cap-react/src/components/drafts/components/DepositFilesList.js

ui: move DepositFileManager to DraftsItemIndex

---

ui/cap-react/src/components/drafts/form/themes/grommet-preview/fields/importDataField.js
ui/cap-react/src/components/drafts/form/themes/grommet/fields/ImportDataFieldSelectComponent.js
ui/cap-react/src/components/drafts/form/themes/grommet/fields/importDataField.js

ui: Improve & update the ImportDataField

---

ui/cap-react/src/components/search/SearchResults.js

ui: add between  SearchResults labels

---

ui/cap-react/src/components/drafts/form/themes/grommet-preview/fields/capFiles.js
ui/cap-react/src/components/drafts/form/themes/grommet/fields/CapFiles.js

ui: add warning to capfiles fields, when file does not exist in the bucket

---

Dockerfile
docker-compose.dev.yml
docker-services.yml

devops: adds docker-compose-dev for debug mode

---

cap/views.py
tests/integration/test_service_pings.py

services: ping fixes and tests

---

cap/modules/fixtures/schemas/cms-questionnaire.json

cms: updating PDF section in cms-stats-questionnaire

---

INSTALL.rst
cap/modules/services/__init__.py

docs: update with docker dev instructions

---

ui/cap-react/src/components/drafts/DraftEditor.js
ui/cap-react/src/components/drafts/DraftPreview.js
ui/cap-react/src/components/drafts/components/DepositFilesList.js
ui/cap-react/src/components/drafts/components/DepositReviews.js
ui/cap-react/src/components/drafts/components/DepositSidebar.js
ui/cap-react/src/components/drafts/components/DraftEditorHeader.js
ui/cap-react/src/components/drafts/components/FileTree/RepoTree.js
ui/cap-react/src/components/drafts/components/FileTree/index.js
ui/cap-react/src/components/drafts/components/tests/DraftEditorHeader.test.js
ui/cap-react/src/components/drafts/form/JSONSchemaPreviewer.js
ui/cap-react/src/components/partials/InfoArrayBox/InfoArrayBox.js
ui/cap-react/src/components/partials/InfoArrayBox/index.js
ui/cap-react/src/components/partials/InfoHeaderBox/InfoHeaderBox.js
ui/cap-react/src/components/partials/InfoHeaderBox/index.js
ui/cap-react/src/components/partials/PermissionBox/index.js
ui/cap-react/src/components/partials/SectionBox.js
ui/cap-react/src/components/published/PublishedPreview.js
ui/cap-react/src/styles/styles.scss

ui: DraftPreview Updates--last

---

ui/cap-react/src/actions/draftItem.js
ui/cap-react/src/actions/published.js
ui/cap-react/src/components/drafts/components/DepositReviews.js
ui/cap-react/src/components/drafts/components/FileTree/index.js
ui/cap-react/src/components/partials/Modal.js
ui/cap-react/src/components/partials/Review/ReviewList/ReviewList.js
ui/cap-react/src/components/partials/Review/ReviewList/index.js
ui/cap-react/src/components/partials/Review/ReviewListItem/ReviewListItem.js
ui/cap-react/src/components/partials/Review/ReviewListItem/index.js
ui/cap-react/src/components/partials/Review/ReviewModal/Review.js
ui/cap-react/src/components/partials/Review/ReviewModal/ReviewModal.js
ui/cap-react/src/components/partials/Review/ReviewModal/ReviewOptions.js
ui/cap-react/src/components/partials/Review/ReviewModal/index.js
ui/cap-react/src/components/published/PublishedPreview.js
ui/cap-react/src/reducers/draftItem.js
ui/cap-react/src/reducers/published.js

refactor: update Review Modal structure

---

ui/cap-react/src/actions/draftItem.js
ui/cap-react/src/components/drafts/DraftPreview.js
ui/cap-react/src/components/partials/Notification.js
ui/cap-react/src/components/published/PublishedPreview.js
ui/cap-react/src/reducers/draftItem.js

 ui : introduce notification banner to draft preview page

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/custom.md
.github/ISSUE_TEMPLATE/feature_request.md
cap/modules/fixtures/schemas/atlas.json
cap/modules/fixtures/schemas/lhcb.json

schemas: updates orcid links in schemas + GitHub issue templates

---

ui/cap-react/src/components/drafts/components/DraftDefaultHeader.js
ui/cap-react/src/components/drafts/components/FileItem.js
ui/cap-react/src/components/drafts/form/JSONSchemaPreviewer.js
ui/cap-react/src/components/partials/FormHeader.js
ui/cap-react/src/components/published/PublishedPreview/PublishedPreview.css
ui/cap-react/src/components/published/PublishedPreview/PublishedPreview.js
ui/cap-react/src/components/published/PublishedPreview/index.js
ui/cap-react/src/styles/styles.scss

ui: update the published preview

---

ui/cap-react/src/components/drafts/components/DepositAccess/PermissionTable.js

ui: fix build error for ui

---

ui/cap-react/src/actions/schemaWizard.js
ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/DraggableBox.js
ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/customizeField.js
ui/cap-react/src/components/cms/components/SchemaWizard/SchemaPreview/SchemaTree/FieldTemplate.js
ui/cap-react/src/components/cms/components/SchemaWizard/SchemaPreview/SchemaTree/HoverBox.js
ui/cap-react/src/components/cms/components/SchemaWizard/SchemaPreview/SchemaTree/ObjectFieldTemplate.js
ui/cap-react/src/components/cms/components/SchemaWizard/SchemaPreview/SchemaTree/renderSortable.js
ui/cap-react/src/components/cms/containers/CustomizeField.js
ui/cap-react/src/reducers/schemaWizard.js
ui/cap-react/src/styles/styles.scss

ui: cms delete item

---

ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/customizeField.js

ui: form builder js error

---

ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/DeletePropertyModal.js
ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/customizeField.js

ui: form builder delete modal propery refactor

---

ui/cap-react/src/components/cms/components/SchemaWizard/SchemaPreview/SchemaTree/ArrayFieldTemplate.js
ui/cap-react/src/components/cms/components/SchemaWizard/SchemaPreview/SchemaTree/FieldTemplate.js
ui/cap-react/src/components/cms/components/SchemaWizard/SchemaPreview/SchemaTree/SchemaTreeItem.js

ui: form builder add hide/show for arrays and nested objects

---

ui/cap-react/src/components/drafts/form/themes/grommet/widgets/TextWidget.js

ui: fix react-select menu position

---

cap/modules/deposit/api.py
cap/modules/deposit/validators.py
cap/modules/experiments/validators.py
cap/modules/fixtures/schemas/cms-questionnaire.json
cap/modules/fixtures/schemas/cms.json
cap/modules/records/api.py
cap/modules/records/errors.py
tests/conftest.py
tests/integration/deposits/test_deposit_validation.py
ui/cap-react/src/components/drafts/form/themes/grommet/templates/ArrayFieldTemplate.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/FieldTemplate.js

* records: fix error in path returned from validation
* cms: adds datasets and triggers validation
* cms: updates dataset path, year, trigger dependencies
* ui: forms - fixes wrong description passed
* ui: forms - required '*' position when no title
* Revert "cms: updating PDF section in cms-stats-questionnaire"

cms: analysis deposit paths, year, triggers  validate

---

cap/modules/schemas/cli.py
ui/cap-react/src/actions/schemaWizard.js
ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/customizeField.js
ui/cap-react/src/components/cms/components/SchemaWizard/SchemaPreview/SchemaTree/ArrayFieldTemplate.js
ui/cap-react/src/components/cms/components/SchemaWizard/SchemaPreview/SchemaTree/ObjectFieldTemplate.js
ui/cap-react/src/components/cms/containers/CustomizeField.js

schemas: cli - fix issue in Choice

---

.travis.yml
cap/config.py
cap/modules/fixtures/schemas/cms-questionnaire_v2.json
cap/modules/fixtures/schemas/ml-applications-development.json
cap/modules/fixtures/schemas/ml-applications-survey.json
cap/modules/fixtures/schemas/ml-applications-use.json
cap/modules/mail/utils.py
tests/conftest.py
tests/unit/mail/test_extra_recipients.py
ui/cap-react/src/components/drafts/DraftPreview.js
ui/cap-react/src/components/drafts/form/themes/grommet/components/FormLayer.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/ArrayFieldTemplate.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/LayerArrayField.js

cms: updates on statistics questionnaire for v2

---

.travis.yml

global: pin 'pip' on travis

---

ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/customizeField.js
ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/index.js
ui/cap-react/src/components/drafts/components/DepositAccess/DepositAccess.js
ui/cap-react/src/components/drafts/components/DepositAccess/PermissionTable.js

* ui: form builder customizeField css updates 
* closes #1978
* closes #1989

ui: fix permnissions box, display delete and add button only to admins 

---

ui/cap-react/src/actions/schemaWizard.js
ui/cap-react/src/components/cms/components/CMSIndex/CreateContentType.js
ui/cap-react/src/components/cms/components/CMSIndex/DropZoneForm.js
ui/cap-react/src/components/cms/components/CMSIndex/SelectContentType.js
ui/cap-react/src/components/cms/components/CMSIndex/createModelForm.js
ui/cap-react/src/components/cms/components/CMSIndex/index.js
ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/SelectFieldType.js
ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/customizeField.js
ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/index.js
ui/cap-react/src/components/cms/components/SchemaWizard/SchemaPreview/SchemaTree/ArrayFieldTemplate.js
ui/cap-react/src/components/cms/components/SchemaWizard/SchemaPreview/SchemaTree/FieldTemplate.js
ui/cap-react/src/components/cms/components/SchemaWizard/SchemaPreview/SchemaTree/SchemaTreeItem.js
ui/cap-react/src/components/cms/components/SchemaWizard/SchemaPreview/index.js
ui/cap-react/src/components/cms/components/SchemaWizard/SettingsModal.js
ui/cap-react/src/components/cms/components/SchemaWizard/index.js
ui/cap-react/src/components/cms/components/utils/schemas.js
ui/cap-react/src/components/cms/containers/SchemaWizard.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/FieldTemplate.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/ObjectFieldTemplate.js
ui/cap-react/src/components/drafts/form/themes/grommet/templates/TabField.js

* closes #1966
* closes #1971
* closes #1982
* closes #1997
* closes #1973
* closes #1976

ui: form builder, fixes for tabfield and objectfield

---

ui/cap-react/src/components/cms/components/SchemaWizard/SchemaPreview/SchemaTree/ArrayFieldTemplate.js
ui/cap-react/src/components/cms/components/SchemaWizard/SchemaPreview/SchemaTree/FieldTemplate.js
ui/cap-react/src/components/cms/components/SchemaWizard/SchemaPreview/SchemaTree/SchemaTreeItem.js

ui: form builder update the button for hide/show for arrays-objs

---

ui/cap-react/src/actions/schemaWizard.js
ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/customizeField.js

ui: remove unused css updates from form builder

---

cap/modules/fixtures/schemas/cms-questionnaire_v2.json

cms: update stats-questionnaire-v2 schema, fixes

---

cap/modules/fixtures/schemas/ml-applications-development.json
setup.py

cms: stat-questionnaire fix 3.a.3.12 dependencies

---

ui/cap-react/src/components/cms/components/SchemaWizard/FormPreview.js
ui/cap-react/src/components/cms/components/SchemaWizard/GuidelinesPopUp.js
ui/cap-react/src/components/cms/components/SchemaWizard/SchemaPreview/SchemaTree/HoverBox.js
ui/cap-react/src/components/cms/components/SchemaWizard/SchemaWizardHeader.js
ui/cap-react/src/components/cms/components/utils/common.js

ui: form builder add empty state for the form

---

ui/cap-react/src/actions/schemaWizard.js
ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/DraggableBox.js
ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/SelectFieldType.js
ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/customizeField.js
ui/cap-react/src/components/cms/components/SchemaWizard/SchemaPreview/SchemaTree/SchemaTreeItem.js
ui/cap-react/src/components/cms/components/SchemaWizard/index.js
ui/cap-react/src/components/cms/components/utils/fieldTypes.js
ui/cap-react/src/components/cms/components/widgets/SelectWidget.js
ui/cap-react/src/components/cms/containers/SchemaWizard.js
ui/cap-react/src/components/cms/containers/SelectFieldType.js
ui/cap-react/src/components/search/SearchPage.js
ui/cap-react/src/reducers/schemaWizard.js

ui: improve the error page, in the schemaWizard

---

cap/modules/deposit/cli.py
tests/integration/cli/test_deposits_create_with_permissions.py
ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/customizeField.js
ui/cap-react/src/reducers/schemaWizard.js

* closes #2049
* closes #2068 
* closes #2066

features: formBuilder updates + deposit-cli create with multiple user/roles

---

cap/config.py
cap/modules/search/facets.py
tests/integration/deposits/test_get_deposits.py

deposits: add nested types with versions in facets

---

cap/config.py
cap/modules/fixtures/schemas/cms.json
ui/cap-react/src/components/search/SearchFacet/FacetItem.js
ui/cap-react/src/components/search/SearchFacet/SubFacet/SubFacet.js
ui/cap-react/src/components/search/SearchFacet/SubFacet/index.js

search: fix facets and cms physics object

---

ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/ActionHeaderBox.js
ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/customizeField.js
ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/index.js
ui/cap-react/src/components/cms/containers/CustomizeField.js
ui/cap-react/src/components/cms/containers/PropertyEditor.js
ui/cap-react/src/components/partials/EditableField.js

ui: propkeyeditor header actions

---

ui/cap-react/src/actions/schemaWizard.js
ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/ActionHeaderBox.js
ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/customizeField.js
ui/cap-react/src/components/cms/components/SchemaWizard/PropertyEditor/index.js
ui/cap-react/src/components/cms/containers/CustomizeField.js
ui/cap-react/src/components/cms/containers/PropertyEditor.js
ui/cap-react/src/components/partials/EditableField.js
ui/cap-react/src/components/settings/components/OAuthPopup.js
ui/cap-react/src/components/welcome/Header.js

* redirect was borken after change to popup window
* closes #2046
Also, 
* closes #2087 
* closes #2088 
* closes #2080 
* closes #2082 

ui: fix redirect to next on login

---

.github/workflows/ui-test.yml
.github/workflows/web-api.yml

tests: pin OS version

---

requirements-local-forks.txt
requirements.txt
setup.py

* https://github.com/Azure/azure-cli/issues/16858

global: fix cryptography installation

---

cap/config.py
cap/modules/deposit/api.py
cap/modules/experiments/utils/cms.py
cap/modules/mail/templates/mail/analysis_review.html
cap/modules/mail/utils.py
scripts/cap.wordlist

* adds more options for cms conveners
* adds mail on review functionality

cms: improve mail procedure, add reviews

---

cap/config.py
cap/modules/deposit/api.py
cap/modules/experiments/utils/cms.py
cap/modules/fixtures/schemas/cms-questionnaire_v2.json
cap/modules/mail/templates/mail/analysis_review.html
cap/modules/mail/utils.py
scripts/cap.wordlist

cms: update mail recipient calculation for stats questionnaire

---

ui/cap-react/src/actions/search.js
ui/cap-react/src/components/search/SearchFacet/FacetItem.js
ui/cap-react/src/components/search/SearchFacet/SearchFacet.js
ui/cap-react/src/components/search/ShowMore/ShowMore.js
ui/cap-react/src/reducers/searchReducer.js

ui: search facet updates

---

ui/cap-react/src/components/cms/components/utils/fieldTypes.js

ui: remove unused masked property form builder

---

ui/cap-react/src/components/settings/Integrations.js
ui/cap-react/src/components/settings/Profile/Profile.js

ui: settings - fix integration boxes + profile.get

---

ui/cap-react/src/components/dashboard/DashboardListItem.js
ui/cap-react/src/components/drafts/components/DraftDefaultHeader.js
ui/cap-react/src/components/search/SearchResults.js

ui: fix empty general title at dashboard

---

cap/modules/deposit/api.py
cap/modules/mail/ext.py
cap/modules/mail/receivers.py
cap/modules/mail/utils.py
tests/unit/mail/test_mail.py

mail: use signals to trigger post notifications

---

ui/cap-react/src/actions/auth.js
ui/cap-react/src/components/create/CreateIndex.js
ui/cap-react/src/components/drafts/DraftPreview.js
ui/cap-react/src/components/drafts/components/CreateForm/CreateForm.js

ui: add only immutable for draft-create

---

cap/modules/mail/utils.py
scripts/cap.wordlist
tests/unit/mail/test_mail.py
tests/unit/mail/test_subject_and_message.py

mail: update mail subject with recid on publish

---

cap/config.py
cap/modules/experiments/utils/cadi.py
cap/modules/experiments/utils/cern_sso.py
cap/modules/experiments/utils/common.py
cap/modules/experiments/validators.py
setup.py
tests/unit/experiments/test_cadi_utils.py

* updates CADI API urls
* adds integration for the new CERN Authentication for CADI
* https://gitlab.cern.ch/authzsvc/tools/auth-get-sso-cookie

cms: fix CADI authentication

---

cap/modules/mail/utils.py
scripts/cap.wordlist

mail: jira plain text mail

---

cap/modules/fixtures/schemas/cms.json
cap/modules/mail/templates/mail/base.html
cap/modules/user/views.py
docs/Dockerfile
docs/README.md
docs/book.json
docs/docker-compose.yml
docs/package.json
docs/support.md
ui/cap-react/src/components/about/AboutPage.js

Also:
* closes #2238 
* closes #2244
* closes #2231
* closes #2242

deposits: fix for case sensitive roles

---

cap/modules/mail/templates/mail/base.html

* addresses #1210
Signed-off-by: Artemis Lavasa <artemis.lavasa@cern.ch>

mail: update template

---

ui/cap-react/src/components/cms/components/utils/fieldTypes.js
ui/cap-react/src/components/drafts/form/themes/grommet-preview/components/FieldHeader.js
ui/cap-react/src/components/drafts/form/themes/grommet/widgets/SelectWidget.js
ui/cap-react/src/components/search/SearchResults.js

* closes #2233
* closes #2236
* closes #2245

ui: merging PR #2233 #2236 #2245

---

LICENSE
README.rst
docs/introduction.md

* changes to GPLv3.0
* adds license note in general docs
* improves verbiage in README
* addresses #2187
Signed-off-by: Artemis Lavasa <artemis.lavasa@cern.ch>

license fix

---

scripts/cap.wordlist

Signed-off-by: Artemis Lavasa <artemis.lavasa@cern.ch>

Additions to wordlist

---

INSTALL.rst
docs/cli.md
docs/introduction.md

docs: adds guides for CLI

---

cap/modules/fixtures/schemas/cms-questionnaire_v2.json
cap/modules/fixtures/schemas/cms.json
ui/cap-react/package.json
ui/cap-react/src/components/partials/Header.js
ui/cap-react/src/components/partials/Menu.js
ui/cap-react/src/components/partials/MenuItem.js
ui/cap-react/src/components/partials/MultipleMenu/MultipleMenu.js
ui/cap-react/src/components/partials/MultipleMenu/MultipleMenus.css
ui/cap-react/src/components/partials/MultipleMenu/MultipleMenus.js
ui/cap-react/src/components/partials/MultipleMenu/index.js
ui/cap-react/src/components/partials/Pagination/Pagination.css
ui/cap-react/src/components/partials/Pagination/Pagination.js
ui/cap-react/src/components/partials/Pagination/index.js
ui/cap-react/src/components/search/SearchPage.js
ui/cap-react/src/components/search/SearchTag/SearchTag.js
ui/cap-react/src/components/search/SortSelect.js
ui/cap-react/src/styles/styles.scss
ui/yarn.lock

* closes #2207 
* closes #2241

Merges PRs #2207 #2241, Updates CMS mappings

---

ui/cap-react/src/actions/published.js
ui/cap-react/src/actions/tests/published.test.js

tests: published action tests

---

cap/modules/fixtures/schemas/cms-physics-object.json
cap/modules/fixtures/schemas/cms.json

schemas: restructure physics objects in cms

---

ui/cap-react/src/components/partials/Menu.js
ui/cap-react/src/components/partials/MenuItem.js
ui/cap-react/src/components/partials/MultipleMenu/MultipleMenu.js
ui/cap-react/src/components/partials/MultipleMenu/MultipleMenus.js
ui/cap-react/src/components/search/SortSelect.js
ui/cap-react/src/components/welcome/Header.js
ui/cap-react/src/styles/styles.scss

ui: update menu style

---

ui/cap-react/src/components/drafts/form/themes/grommet-preview/templates/FieldTemplate.js

ui: update preview ui for rich editor

---

cap/config.py
cap/modules/deposit/ext.py
cap/modules/deposit/serializers/json.py
cap/modules/deposit/utils.py
cap/modules/fixtures/schemas/alice-analysis.json
cap/modules/fixtures/schemas/atlas.json
cap/modules/fixtures/schemas/cms-questionnaire.json
cap/modules/fixtures/schemas/cms-questionnaire_v2.json
cap/modules/fixtures/schemas/cms.json
cap/modules/fixtures/schemas/lhcb.json
cap/modules/records/serializers/__init__.py
cap/modules/records/serializers/json.py
cap/modules/records/serializers/schemas/common.py
cap/modules/records/serializers/schemas/json.py
tests/conftest.py
tests/integration/deposits/test_get_deposits.py
tests/unit/experiments/test_cadi_utils.py
ui/cap-react/src/components/search/SearchFacet/FacetItem.js
ui/cap-react/src/components/search/SearchFacet/SubFacet/SubFacet.js
ui/cap-react/src/components/search/SearchFacets.js

* closes #2141 
* closes #2190

records: add schema collection on record index

---

.github/workflows/e2e-workflow.yml
cap/config.py
cap/modules/schemas/cli.py
docker-compose.e2e.yml
docker-services.yml

global: add GH workflow for cap-client

---

.github/workflows/e2e-workflow.yml
Dockerfile

tests: add pytest vcr for e2e testing of cap-client

---

ui/cap-react/src/components/drafts/components/DraftDefaultHeader.js

ui: disable ediatble title if published

---

ui/cap-react/src/components/drafts/components/DepositAccess/PermissionPopUp.js
ui/cap-react/src/components/drafts/components/DepositAccess/PermissionTable.js

ui: draft permissions owner blocked

---

ui/cap-react/src/antd/drafts/components/Drafts/Drafts.js
ui/cap-react/src/antd/partials/Error/Error.js
ui/cap-react/src/antd/partials/Error/index.js

ui: ant draft error handling

---

cap/modules/records/serializers/json.py

records: fix display name in search aggs

---

ui/cap-react/src/actions/search.js
ui/cap-react/src/components/search/SearchFacets.js
ui/cap-react/src/components/search/SearchTag/SearchTag.js

ui: search update to accept collection + fix

---

ui/cap-react/src/antd/create/Create.js
ui/cap-react/src/antd/create/CreateContainer.js
ui/cap-react/src/antd/create/index.js
ui/cap-react/src/antd/drafts/CreateForm/CreateForm.js
ui/cap-react/src/antd/drafts/components/Connect/Connect.js
ui/cap-react/src/antd/drafts/components/Connect/RepoActions.js
ui/cap-react/src/antd/drafts/components/Connect/index.js
ui/cap-react/src/antd/drafts/components/Connect/utils/index.js
ui/cap-react/src/antd/drafts/components/Drafts/Drafts.js
ui/cap-react/src/antd/drafts/containers/Connect.js
ui/cap-react/src/antd/index/IndexPage.js
ui/cap-react/src/antd/partials/EditableField/EditableField.js

* closes #2398 
* closes #2385

ui: ant updates - draft connect, createIndex

---

ui/cap-react/src/antd/App/App.js
ui/cap-react/src/antd/about/About.js
ui/cap-react/src/antd/drafts/components/Drafts/Drafts.js
ui/cap-react/src/antd/partials/DocumentTitle/DocumentTitle.js
ui/cap-react/src/antd/partials/DocumentTitle/index.js
ui/cap-react/src/antd/policy/Policy.js
ui/cap-react/src/antd/settings/index.js

ui: ant partials Title

---

requirements.txt

global: pin versions 'reana' packages

---

ui/cap-react/src/antd/partials/Header/Header.less
ui/cap-react/src/antd/partials/Header/LoggedInMenu/LoggedInMenu.js
ui/cap-react/src/antd/partials/HowToSearch/HowToSearch.js
ui/cap-react/src/antd/partials/HowToSearch/index.js
ui/cap-react/src/antd/search/components/Facets.js

ui: ant general fixes

---

docker-services.yml
docker/postgres/Dockerfile

global: bump postgres version to 12.5

---

ui/cap-react/src/antd/forms/Form.less
ui/cap-react/src/antd/forms/templates/Field/FieldTemplate.js
ui/cap-react/src/antd/forms/templates/TabField.js
ui/cap-react/src/antd/forms/templates/TabFieldMenu.js

ui: ant field template fix

---

cap/modules/experiments/utils/cern_sso.py

* updates Kerberos button element ID, after
change from auth service

global: fix get_cern_sso_cookiee method

---

ui/cap-react/src/components/drafts/components/CreateForm/CreateForm.js

ui: remove cms analysis from create

---

cap/modules/fixtures/schemas/cms.json
cap/modules/fixtures/schemas/lhcb.json
ui/cap-react/src/actions/draftItem.js
ui/cap-react/src/actions/published.js
ui/cap-react/src/antd/forms/widgets/SelectWidget.js

ui: ant - PRs #2480, #2477 + extra fixes

---

cap/modules/schemas/models.py
cap/modules/schemas/serializers.py
cap/modules/schemas/views.py
tests/integration/test_schemas_views.py

* closes #2471 
* fixes some code issues

schemas: endpoint to return schema versions 

---

ui/cap-react/src/actions/draftItem.js
ui/cap-react/src/antd/drafts/components/Editor/Editor.js
ui/cap-react/src/antd/drafts/components/Editor/Header.js
ui/cap-react/src/antd/drafts/containers/EditorHeader.js

ui: remove unused code from draft editor

---

cap/config.py

devops: add configuration for superuser groups

---

ui/cap-react/src/components/drafts/components/CreateForm/CreateForm.js

ui: tests - fix create form for e2e

---

ui/cap-react/src/components/drafts/form/themes/grommet/templates/LayerArrayField.js

ui: layer array undefined title fixed

---

ui/cap-react/src/actions/common.js
ui/cap-react/src/antd/collection/Collection.js
ui/cap-react/src/antd/collection/Collection.less
ui/cap-react/src/antd/collection/CollectionPermissionItem.js
ui/cap-react/src/antd/collection/CollectionPermissions.js
ui/cap-react/src/antd/collection/index.js
ui/cap-react/src/antd/dashboard/utils/index.js
ui/cap-react/src/antd/drafts/components/SideBar/SideBar.js
ui/cap-react/src/antd/index/IndexPage.js

Ant collection page

---

cap/modules/deposit/validator/__init__.py
cap/modules/deposit/validator/users.py
tests/integration/deposits/test_deposit_validation.py

closes https://github.com/cernanalysispreservation/analysispreservation.cern.ch/issues/2548

deposit: add schema field update validator

---

cap/modules/auth/views.py
cap/modules/deposit/api.py
cap/modules/services/views/orcid.py
cap/modules/services/views/zenodo.py
tests/integration/auth/test_auth_views.py
tests/integration/deposits/test_clone_deposits.py
tests/integration/repos/test_upload_with_github.py
tests/integration/services/test_orcid_api.py
tests/integration/test_permissions_api.py
tests/integration/test_review_deposit.py

deposit: add error handling

---

ui/cap-react/src/actions/draftItem.js
ui/cap-react/src/antd/drafts/components/Connect/Connect.js
ui/cap-react/src/antd/drafts/components/Editor/Editor.js
ui/cap-react/src/antd/drafts/components/Editor/Header.js
ui/cap-react/src/antd/forms/templates/ArrayFieldTemplates/ArrayUtils.js
ui/cap-react/src/antd/forms/templates/ArrayFieldTemplates/ImportListModal.js
ui/cap-react/src/antd/forms/templates/ObjectFieldTemplate.js
ui/cap-react/src/antd/published/components/Published.js
ui/cap-react/src/antd/search/components/FacetItem.js
ui/cap-react/src/antd/search/components/Header.js

ui: ant - fix lint errors

---

ui/cap-react/src/antd/forms/templates/ArrayFieldTemplates/NormalArrayFieldTemplate.js
ui/cap-react/webpack.config.prod.js

ui: ant - update webpack config for prod

---

docker-services.yml
ui/cap-react/src/components/drafts/components/DepositAccess/DepositAccess.js
ui/cap-react/src/components/drafts/components/DepositAccess/DepositAccessModal.js
ui/cap-react/src/components/drafts/components/DepositAccess/PermissionTable.js
ui/cap-react/src/components/drafts/form/themes/grommet/fields/CernUsersField.js
ui/cap-react/src/components/drafts/form/themes/grommet/fields/index.js

ui: add users component - papadopan #2540

---

cap/modules/experiments/utils/cern_sso.py
cap/modules/experiments/utils/old_cern_sso.py
setup.py

global: fix CERN SSO cookie getter

---

ui/cap-react/src/actions/files.js
ui/cap-react/src/antd/drafts/components/FileManager/FileManager.js
ui/cap-react/src/antd/forms/fields/TitleField.js
ui/cap-react/src/antd/forms/fields/cernUsers.js
ui/cap-react/src/antd/forms/templates/ArrayFieldTemplates/NormalArrayFieldTemplate.js

ui: ant - adds "send email" feature for user/egroup lists

---

.github/workflows/web-api.yml
MANIFEST.in
scripts/ci/commit-msg-check.sh
scripts/ci/commit-msg-spellcheck.sh
scripts/ci/prebuild.sh

global: fix commit linting in github actions

---

requirements-local-forks.txt

files: temp fix for files ensure stream warning

---

scripts/cap.wordlist
tests/conftest.py
tests/integration/deposits/test_publish_deposit.py
tests/integration/repos/test_disconnect_webhook_action.py

tests: change the test db to postgresql

---

ui/cap-react/src/components/drafts/components/DepositAccess/DepositAccessModal.js
ui/cap-react/src/components/drafts/components/DepositAccess/PermissionTable.js

ui: fix permissions people modal

---

cap/modules/deposit/api.py
cap/modules/deposit/loaders.py
cap/modules/deposit/minters.py
cap/modules/deposit/utils.py
cap/modules/records/minters.py
cap/modules/records/serializers/json.py
cap/modules/records/serializers/schemas/common.py
cap/modules/records/utils.py
scripts/cap.wordlist
tests/integration/deposits/test_create_deposit.py
tests/integration/deposits/test_publish_deposit.py

records: auto-increment PID for records/deposits 

---

INSTALL.rst

docs: add receipe for statping user creation

---

docs/github_connect.md

docs: add a guide for the Github integration

---

.github/workflows/e2e-workflow-server.yml
.github/workflows/e2e-workflow-ui.yml
.github/workflows/e2e-workflow.yml
.github/workflows/lint-commit.yml
.github/workflows/lint-push.yml
.github/workflows/ui-test.yml
.github/workflows/web-api.yml
.pre-commit-config.yaml
docker-compose.e2e-override-ui.yml
requirements.txt
run-tests.sh
scripts/cap.wordlist
setup.py

from #2624: lobal: update flow of checks + bump uwsgi version

---

cap/modules/deposit/minters.py
cap/modules/deposit/utils.py
cap/modules/records/utils.py
tests/integration/deposits/test_create_deposit.py
tests/integration/deposits/test_publish_deposit.py

* closes #2640 
* closes #2632

PR #2640 + updates on schema config pid structure

---

cap/config.py
cap/modules/search/sorter.py
tests/integration/deposits/test_get_deposits.py

search: sorting script for sorting analysis stage

---

cap/modules/services/views/status_checks.py
docker/statping/app/template-services.yml
docker/statping/statping.py

services: implement public health check endpoints

---

scripts/cap.wordlist
setup.py

global: pin for swagger-spec-validator dependency

---

cap/modules/deposit/serializers/schemas/json.py
cap/modules/deposit/utils.py
docker-compose.e2e.yml
scripts/cap.wordlist
tests/integration/deposits/test_get_deposits.py
tests/unit/deposit/test_cap_deposit.py
tests/unit/deposit/test_deposit_utils.py

* closes #2623 
* closes #2561

deposits: add 'x-cap-permission' info on the form serializer PR 2623  

---

cap/modules/deposit/api.py
cap/modules/deposit/errors.py
cap/modules/deposit/loaders.py
cap/modules/deposit/utils.py
scripts/cap.wordlist
tests/integration/deposits/test_create_deposit.py
tests/unit/deposit/test_deposit_utils.py

deposits: implement x cap copy finder fields

---

ui/cap-react/src/antd/App/App.js
ui/cap-react/src/antd/partials/ShowMore/ShowMore.js
ui/cap-react/src/antd/search/components/Facet.js
ui/cap-react/src/antd/search/components/FacetItem.js
ui/cap-react/src/antd/search/components/Facets.js
ui/cap-react/src/antd/search/components/Search.js
ui/cap-react/src/antd/search/components/Slider.js

ui: search update state to immutablejs Map, etc

---

.github/workflows/docker-build-server.yml

devops: fix image build issue

---

.pre-commit-config.yaml
.prettierignore
tests/integration/deposits/test_get_deposits.py
ui/cap-react/package.json
ui/cap-react/src/antd/admin/components/Header.js
ui/cap-react/src/antd/forms/templates/ArrayFieldTemplates/NormalArrayFieldTemplate.js
ui/cap-react/src/antd/forms/templates/Field/FieldTemplate.js
ui/cap-react/src/antd/forms/widgets/TextWidget.js
ui/cap-react/src/antd/schemas/Schemas.js
ui/cap-react/src/antd/util/CodeEditor.js
ui/cap-react/src/antd/util/CodeViewer.js
ui/yarn.lock

PR #2680 + test fixes + rebased

---

ui/cap-react/src/antd/admin/components/SchemaTree.js
ui/cap-react/src/antd/admin/formComponents/ArrayFieldTemplate.js
ui/cap-react/src/antd/admin/formComponents/FieldTemplate.js
ui/cap-react/src/antd/admin/formComponents/ObjectFieldTemplate.js
ui/cap-react/src/antd/admin/formComponents/SchemaTreeItem.js
ui/cap-react/src/antd/admin/formComponents/widgets/index.js
ui/cap-react/src/antd/admin/utils/index.js
ui/cap-react/src/antd/forms/Form.js
ui/cap-react/src/antd/forms/fields/TagsField.js

- The items inside arrays are now displayed correctly inside arrays
- When adding a JSON object inside of an array, it is also shown (it didn't show anything before)
- Added a missing check in the tags field since it was throwing an error when initializing the tags of type object if they where empty
Closes #2686

ui: display arrays' content correctly in the tree

---

ui/cap-react/src/antd/admin/formComponents/ArrayFieldTemplate.js
ui/cap-react/src/antd/admin/formComponents/DropArea.js
ui/cap-react/src/antd/admin/formComponents/FieldTemplate.js
ui/cap-react/src/antd/admin/formComponents/HoverBox.js
ui/cap-react/src/antd/admin/formComponents/SchemaTreeItem.js
ui/cap-react/src/antd/admin/formComponents/SortableBox.js

Changed a bit how the dropping of items work. This way it's visually more clear and uniform between all field types.
Closes #2679 
Signed-off-by: Miguel Garcia Garcia <miguel.garcia.garcia@cern.ch>

ui: make the admin drop area more visual 

---

requirements.txt
setup.py
tests/integration/deposits/test_create_deposit.py

global: update json schema dependency

---

ui/cap-react/src/antd/drafts/components/Editor/Editor.js

Closes: #2721 
Signed-off-by: Miguel Garcia Garcia <miguel.garcia.garcia@cern.ch>

ui: fix debounce issue when saving form on antd

---

cap/modules/deposit/utils.py

deposits: fix copy-to method issue

---

ui/cap-react/src/antd/admin/utils/fieldTypes.js
ui/cap-react/src/antd/forms/widgets/UriWidget.js
ui/cap-react/src/antd/forms/widgets/index.js

ui: add goto and copy buttons to uri field

---

cap/modules/schemas/imp.py
cap/modules/schemas/permissions.py
cap/modules/user/views.py
tests/integration/test_user_api.py

global: add roles info in /me endpoint

---

cap/modules/schemas/utils.py
cap/modules/schemas/views.py
tests/integration/schemas/test_schemas_views.py

schemas: add GET/PATCH endpoint for notifications config

---

ui/cap-react/src/antd/admin/notifications/components/NotificationEdit.js
ui/cap-react/src/antd/admin/notifications/components/NotificationList.js
ui/cap-react/src/antd/admin/notifications/components/Notifications.js
ui/cap-react/src/antd/admin/notifications/utils/index.js
ui/cap-react/src/antd/forms/fields/SchemaPathSuggester.js
ui/cap-react/src/antd/forms/fields/containers/SchemaPathSuggester.js
ui/cap-react/src/antd/forms/fields/index.js

ui: create json path suggester component

---

.github/workflows/harbour-build-server.yml
.github/workflows/harbour-build-ui.yml
MANIFEST.in
docker/harbour/backend/Dockerfile
docker/harbour/ui/Dockerfile

- Tested in a personal project with a push on my branch. Looks fine!
closes #2790

devops: upgrade image deployment from workflows

---

.github/workflows/e2e-workflow-server.yml
.github/workflows/e2e-workflow-ui.yml
.github/workflows/e2e-workflow.yml
.github/workflows/lint-commit.yml
.github/workflows/lint-push.yml
.github/workflows/ui-test.yml
.github/workflows/web-api.yml

devops: update workflows for branch next

---

docker/nginxdev/default.conf

global: disable etag in nginx

---

ui/cap-react/src/antd/collection/CollectionPermissions.js

ui: add also records to collection permissions

---

tests/integration/deposits/test_files_for_deposit.py

tests: check bucket is locked in published state

---

ui/cap-react/src/antd/forms/Form.less

* removes unnecessary  background color
* fixes select options for large text

ui: forms - select options to wrap on large text

---

ui/cap-react/src/antd/forms/widgets/SelectWidget.js
ui/cap-react/src/antd/forms/widgets/index.js
ui/cap-react/src/style.less

ui: fix suggestions and multiselect in select fields

---

ui/cap-react/src/antd/forms/widgets/SelectWidget.js

ui: fix filtering when using es query syntax
